/**
 * The 19 x 19 handedness GRID measured on `main` — the baseline `test/glyph-chirality.test.ts`
 * holds the visual-polish redraw to: no family may become handed at a grid cell where `main` was
 * symmetric.
 *
 * Measured on a `git archive` of `main` @ 22bce44 with ONLY `src/elements/glyph-chirality.ts`'s
 * key changed to the tie-robust one this branch ships (`keyNum`: `fmt4` after a 1e-7 mm nudge off
 * the `x.xxxx5` rounding ties), by `npx tsx test/handedness-survey.ts <that extract> --grid` — the
 * survey's own predicate, so the two sides are read by the same instrument. Main's own key gives
 * the same table on main (it has no tie-sensitive glyph); the tip's redrawn glyphs do have them,
 * which is why the comparison must not mix the two keys.
 *
 * Each entry is `surveyGrid`'s: `"all"` / `"none"` when every cell agrees, else one row per offset
 * (0, 100, 1000) x width (`GRID_SIDES`), one character per depth (`GRID_SIDES`) — `H` handed. Never
 * re-measure this table to green the test.
 */
export const GRID_ON_MAIN: Readonly<Record<string, "all" | "none" | readonly string[]>> = {
  wc: "none",
  basin: "none",
  shower: "none",
  bathtub: "all",
  kitchen_sink: "none",
  counter: [
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "...................",
  ],
  stove: "none",
  fridge: [
    "...................",
    "...................",
    "...................",
    "H..................",
    "HH.................",
    "HH.................",
    "HHH................",
    "HHHHH..............",
    "HHHHHH.............",
    "HHHHHH.............",
    "HHHHHHH............",
    "HHHHHHHH...........",
    "HHHHHHHHH..........",
    "HHHHHHHHHH.........",
    "HHHHHHHHHHHH.......",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHHH....",
    "HHHHHHHHHHHHHHHHH..",
    "...................",
    "...................",
    "...................",
    "H..................",
    "HH.................",
    "HH.................",
    "HHH................",
    "HHHHH..............",
    "HHHHHH.............",
    "HHHHHH.............",
    "HHHHHHH............",
    "HHHHHHHH...........",
    "HHHHHHHHH..........",
    "HHHHHHHHHH.........",
    "HHHHHHHHHHHH.......",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHHH....",
    "HHHHHHHHHHHHHHHHH..",
    "...................",
    "...................",
    "...................",
    "H..................",
    "HH.................",
    "HH.................",
    "HHH................",
    "HHHHH..............",
    "HHHHHH.............",
    "HHHHHH.............",
    "HHHHHHH............",
    "HHHHHHHH...........",
    "HHHHHHHHH..........",
    "HHHHHHHHHH.........",
    "HHHHHHHHHHHH.......",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHHH....",
    "HHHHHHHHHHHHHHHHH..",
  ],
  bed: "all",
  double_bed: "all",
  nightstand: "none",
  wardrobe: "none",
  sofa: "none",
  armchair: "none",
  coffee_table: "none",
  tv_unit: "none",
  table: "none",
  dining_table: "none",
  chair: "none",
  stool: "none",
  bench: "none",
  desk: "all",
  office_chair: "none",
  bookshelf: "none",
  oven: "none",
  dishwasher: "none",
  island: "all",
  upper_cabinet: [
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "HHHHHHHHHHHHHHHHHHH",
    "...................",
    "...................",
  ],
  washer: "all",
  dryer: "none",
  plant: "none",
  car: "none",
  rug: "none",
  sofa_l: "all",
  piano: "all",
  sun_lounger: "none",
  tree: "none",
  conifer: "none",
  shrub: "all",
  hedge: [
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "H..................",
    "HH.................",
    ".HH................",
    "..H................",
    "..HH...............",
    "H..HH..............",
    ".H.HHH.............",
    "..H.HHH............",
    "H.H..HH............",
    "H.H.H..HHH.........",
    "H..H.HH...HH.......",
    ".HH.H..H..HHH......",
    "HHH.H.H.HH..HH.....",
    "HH..H.H.HH.H..H....",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "H..................",
    "HH.................",
    ".HH................",
    "..H................",
    "..HH...............",
    "H..HH..............",
    ".H.HHH.............",
    "..H.HHH............",
    "H.H..HH............",
    "H.H.H..HHH.........",
    "H..H.HH...HH.......",
    ".HH.H..H..HHH......",
    "HHH.H.H.HH..HH.....",
    "HH..H.H.HH.H..H....",
    "...................",
    "...................",
    "...................",
    "...................",
    "...................",
    "H..................",
    "HH.................",
    ".HH................",
    "..H................",
    "..HH...............",
    "H..HH..............",
    ".H.HHH.............",
    "..H.HHH............",
    "H.H..HH............",
    "H.H.H..HHH.........",
    "H..H.HH...HH.......",
    ".HH.H..H..HHH......",
    "HHH.H.H.HH..HH.....",
    "HH..H.H.HH.H..H....",
  ],
  bbq: "all",
  outdoor_table: "none",
  outdoor_chair: "none",
  umbrella: "none",
  bicycle: "all",
  motorcycle: [
    "H..................",
    "HH.................",
    "HHH................",
    "HHHH...............",
    "HHHHH..............",
    "HHHHHH.............",
    "HHHHHHH............",
    "HHHHHHHH...........",
    "HHHHHHHHH..........",
    "HHHHHHHHHH.........",
    "HHHHHHHHHHH........",
    "HHHHHHHHHHHH.......",
    "HHHHHHHHHHHHH......",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHHH....",
    "HHHHHHHHHHHHHHHH...",
    "HHHHHHHHHHHHHHHHH..",
    "HHHHHHHHHHHHHHHHHH.",
    "HHHHHHHHHHHHHHHHHHH",
    "H..................",
    "HH.................",
    "HHH................",
    "HHHH...............",
    "HHHHH..............",
    "HHHHHH.............",
    "HHHHHHH............",
    "HHHHHHHH...........",
    "HHHHHHHHH..........",
    "HHHHHHHHHH.........",
    "HHHHHHHHHHH........",
    "HHHHHHHHHHHH.......",
    "HHHHHHHHHHHHH......",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHHH....",
    "HHHHHHHHHHHHHHHH...",
    "HHHHHHHHHHHHHHHHH..",
    "HHHHHHHHHHHHHHHHHH.",
    "HHHHHHHHHHHHHHHHHHH",
    "H..................",
    "HH.................",
    "HHH................",
    "HHHH...............",
    "HHHHH..............",
    "HHHHHH.............",
    "HHHHHHH............",
    "HHHHHHHH...........",
    "HHHHHHHHH..........",
    "HHHHHHHHHH.........",
    "HHHHHHHHHHH........",
    "HHHHHHHHHHHH.......",
    "HHHHHHHHHHHHH......",
    "HHHHHHHHHHHHHH.....",
    "HHHHHHHHHHHHHHH....",
    "HHHHHHHHHHHHHHHH...",
    "HHHHHHHHHHHHHHHHH..",
    "HHHHHHHHHHHHHHHHHH.",
    "HHHHHHHHHHHHHHHHHHH",
  ],
  hot_tub: "none",
  swing: "none",
  trampoline: "none",
  bin: "none",
  mailbox: "all",
  ev_charger: "all",
  pergola: "none",
  sandpit: "none",
  fire_pit: "none",
  shed: "none",
  clothesline: "none",
  bidet: "none",
  urinal: "none",
  laundry_sink: "none",
  water_heater: "none",
  mirror: "all",
  range_hood: "none",
  microwave: "all",
  bar_counter: "none",
  bunk_bed: "none",
  crib: "none",
  dresser: "none",
  vanity: "none",
  fireplace: "none",
  radiator: "none",
  sideboard: "none",
  loveseat: "none",
  chaise: "all",
  tv: "none",
  coat_rack: "none",
  shoe_cabinet: "all",
  meeting_table: "none",
  reception_desk: "all",
  filing_cabinet: "none",
  locker: "none",
  pool_table: "none",
  treadmill: "none",
};
