// Copy the canonical repo docs into the VitePress site as page sources, and
// regenerate the example-gallery SVGs from examples/*.arch, so the site is always
// generated from the single source of truth (docs/*.md, examples/*.arch) and
// never drifts. Run automatically before `dev`/`build` via the npm scripts.
//
// Requires the core to be built first (`npm run build` at the repo root) so the
// gallery can compile the examples through the published entry point.
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");

// VitePress publishes public/ verbatim at the site root. Create it up front so
// page() can also drop a raw-markdown copy of each generated page there.
const publicDir = join(here, "public");
mkdirSync(publicDir, { recursive: true });

/**
 * Copy a canonical doc into the site as a page source (with a "generated" banner),
 * AND publish the raw canonical markdown at `/<route>.md` (public/<dest>) so a tool
 * can fetch the plain source of any doc page by appending `.md` — the same
 * append-`.md` convention llms.txt advertises. The raw copy is the unbannered body,
 * i.e. exactly the repo's canonical markdown, so machines get clean text.
 */
function page(src, dest) {
  const body = readFileSync(join(repo, src), "utf8");
  const banner = `> _This page is generated from [\`${src}\`](https://github.com/chanmeng666/archlang/blob/main/${src}) — edit it there._\n\n`;
  writeFileSync(join(here, dest), banner + body);
  writeFileSync(join(publicDir, dest), body); // raw markdown at /<route>.md
  // eslint-disable-next-line no-console
  console.log(`  ${src} → ${dest}  (+ /${dest})`);
}

console.log("syncing canonical docs into the site:");
page("docs/language-reference.md", "reference.md");
page("docs/cli-reference.md", "cli.md");
page("docs/furniture.md", "furniture.md");
page("docs/analysis.md", "analysis.md");
page("docs/intent.md", "intent.md");
page("docs/error-codes.md", "errors.md");
page("spec.llm.md", "spec.md");

// Serve the llms.txt map + the bundled full-context artifact at the site root
// (per llmstxt.org: /llms.txt and /llms-full.txt). Both are generated from the
// single sources of truth at the repo root (llms.txt hand-maintained;
// llms-full.txt by `npm run gen:llms`); VitePress publishes public/ at root.
for (const f of ["llms.txt", "llms-full.txt"]) {
  copyFileSync(join(repo, f), join(publicDir, f));
  console.log(`  ${f} → public/${f}`);
}

// Machine-native authoring artifacts, served at the site root so a tool can fetch
// them directly (advertised in llms.txt): the Plan-JSON schema and the GBNF
// constrained-decoding grammar. Both are generated at the repo root
// (`npm run gen:plan-schema` / `npm run gen:gbnf`); copied flat here.
for (const [src, dest] of [
  ["schemas/plan.schema.json", "plan.schema.json"],
  ["schemas/intent.schema.json", "intent.schema.json"],
  ["grammars/archlang.gbnf", "archlang.gbnf"],
]) {
  copyFileSync(join(repo, src), join(publicDir, dest));
  console.log(`  ${src} → public/${dest}`);
}

// ADRs: copy each, plus build an index.
const adrSrc = join(repo, "docs/adr");
const adrDest = join(here, "adr");
mkdirSync(adrDest, { recursive: true });
const adrs = readdirSync(adrSrc)
  .filter((f) => f.endsWith(".md") && f !== "index.md")
  .sort();
for (const f of adrs) copyFileSync(join(adrSrc, f), join(adrDest, f));
const adrEntries = adrs.map((f) => {
  const first = readFileSync(join(adrSrc, f), "utf8")
    .split("\n")
    .find((l) => l.startsWith("# "));
  // Strip the "ADR NNNN — " prefix: the sidebar is already an ordered ADR list.
  const title = (first ? first.replace(/^#\s*/, "") : f).replace(/^ADR\s*\d+\s*[—-]\s*/i, "");
  return { text: title, link: `/adr/${f.replace(/\.md$/, "")}` };
});
const index =
  "# Architecture Decision Records\n\nKey design decisions behind ArchLang, with their context and trade-offs.\n\n" +
  adrEntries.map((e) => `- [${e.text}](${e.link})`).join("\n") +
  "\n";
writeFileSync(join(adrDest, "index.md"), index);
// Emit the ADR sidebar as data so .vitepress/config.ts never hand-lists them. The
// hand-written list had frozen at 0005 while docs/adr/ grew to 0014 — same rot as the
// stale CLI docs, same fix: derive it from the source of truth.
writeFileSync(
  join(here, ".vitepress", "theme", "adr-data.js"),
  "// GENERATED by sync-docs.mjs from docs/adr/*.md — do not edit.\n" +
    `export const ADRS = ${JSON.stringify(adrEntries, null, 2)};\n`,
);
console.log(`  ${adrs.length} ADRs → adr/  (+ .vitepress/theme/adr-data.js)`);

// Example gallery: compile each example to SVG through the built core, and emit a
// data module with each example's *source* so the docs pages can seed live,
// editable `<ArchLive>` widgets from the same single source of truth.
const exDest = join(here, "public", "examples");
mkdirSync(exDest, { recursive: true });
const examples = ["studio", "two-bed", "parametric", "themed", "relational", "attached", "accessible"];
const sources = {};
for (const name of examples) {
  sources[name] = readFileSync(join(repo, "examples", `${name}.arch`), "utf8");
}
// Always write the source data (needed for the live widgets even if the core
// isn't built yet — the widget compiles at runtime in that case).
writeFileSync(
  join(here, ".vitepress", "theme", "examples-data.js"),
  "// GENERATED by sync-docs.mjs from examples/*.arch — do not edit.\n" +
    `export const EXAMPLES = ${JSON.stringify(sources, null, 2)};\n`,
);
console.log(`  ${examples.length} example sources → .vitepress/theme/examples-data.js`);
try {
  const { compile } = await import(pathToFileURL(join(repo, "dist", "index.js")).href);
  for (const name of examples) {
    const { svg, diagnostics } = compile(sources[name], { noCache: true });
    const errs = diagnostics.filter((d) => d.severity === "error");
    if (errs.length) throw new Error(`${name}.arch: ${errs[0].message}`);
    writeFileSync(join(exDest, `${name}.svg`), svg);
  }
  console.log(`  ${examples.length} example SVGs → public/examples/`);
} catch (e) {
  console.warn(`  ! skipped example SVGs (run \`npm run build\` at repo root first): ${e.message}`);
}
