import { defineConfig, type HeadConfig } from "vitepress";
// Generated by sync-docs.mjs (which the dev/build npm scripts run first) from docs/adr/.
import { ADRS } from "./theme/adr-data.js";
import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

// The ArchLang TextMate grammar — generated from the single source of truth
// (scripts/gen-grammars.ts → editors/archlang.tmLanguage.json, the same grammar
// VS Code uses). Loading it here lets Shiki highlight `arch` fenced code blocks
// instead of falling back to plain text, and keeps the site in lockstep with the
// grammar (regenerate the grammar → the site picks it up; nothing to hand-sync).
const archGrammar = JSON.parse(
  readFileSync(fileURLToPath(new URL("../../editors/archlang.tmLanguage.json", import.meta.url)), "utf8"),
);

// The one light source-world syntax palette (ADR 0014). Same eight hexes as the
// `--syn-*` tokens in theme/style.css and the fallbacks in scripts/gen-grammars.ts
// — all ≥4.5:1 on the code-fence grounds (--src-bg #eceef2 / --src-surface #fbfbfc).
// A SINGLE theme (not a {light,dark} pair) makes Shiki emit plain `color:#hex`
// with no --shiki-* vars to swap. Neither stock light theme was usable: github-light's
// comment (#6e7781) is 4.40:1 on our grounds, and github-light-high-contrast's keyword
// is red — which would collide with "redline means attention only".
const archlangLight = {
  name: "archlang-light",
  type: "light" as const,
  colors: { "editor.background": "#eceef2", "editor.foreground": "#1a1d23" },
  tokenColors: [
    { scope: ["comment", "punctuation.definition.comment"], settings: { foreground: "#5a616e", fontStyle: "italic" } },
    { scope: ["string", "constant.other.symbol"], settings: { foreground: "#8a5a00" } },
    { scope: ["constant.numeric", "constant.language.boolean"], settings: { foreground: "#0f6f7a" } },
    { scope: ["constant.language", "constant.character", "variable.language"], settings: { foreground: "#0b57d0" } },
    { scope: ["keyword", "storage.modifier"], settings: { foreground: "#6b3ae0", fontStyle: "bold" } },
    {
      scope: ["storage.type", "entity.name.type", "entity.name.class", "support.type", "support.class"],
      settings: { foreground: "#9a4a06", fontStyle: "bold" },
    },
    {
      scope: ["entity.name.function", "support.function", "entity.name.tag", "variable.other.property"],
      settings: { foreground: "#14602a" },
    },
    { scope: ["keyword.operator", "punctuation"], settings: { foreground: "#464d59" } },
    { scope: ["variable", "entity.name", "meta.definition.variable"], settings: { foreground: "#1a1d23" } },
  ],
};

// ───────────────────────────────────────────────────────────────────────────────
// PER-PAGE METADATA — the one place this site's SEO/GEO text is written.
//
// Before this table the site shipped ONE <title>, ONE description and ONE social
// card for all 34 routes, no canonical and no structured data, so every page
// looked identical to a crawler and to an answer engine. The strings below are
// EDITORIAL — they cannot be derived from a generator, because "what does this
// page answer" is not a fact the compiler holds — which is exactly why they ship
// with a mechanical guard: `test/docs-page-meta.test.ts` asserts the table covers
// every route VitePress builds and nothing it does not, that every description is
// a sentence of 80–170 characters, and that none of them carries a killed claim or
// a hype word. Read it before editing a row.
//
// Shape law: one `["<route>", "<title>", "<description>"],` row per route, literal
// and top-level, because that test parses this table out of this file rather than
// importing it (config.ts imports `./theme/adr-data.js`, which only exists after a
// docs sync — a test that imported it would fail on a fresh checkout).
// ───────────────────────────────────────────────────────────────────────────────

const SITE_ORIGIN = "https://archlang.uk";
const OG_IMAGE = `${SITE_ORIGIN}/brand/archlang-og.png`;
const REPO_URL = "https://github.com/ChanMeng666/archlang";
const MIT_LICENSE = "https://opensource.org/licenses/MIT";
/** Author and publisher of everything on this host. A person, not an organisation. */
const AUTHOR = { name: "Chan Meng", url: "https://github.com/ChanMeng666" };

/** The published core's version, read once at config load — never retyped. */
const CORE_VERSION: string = JSON.parse(
  readFileSync(fileURLToPath(new URL("../../package.json", import.meta.url)), "utf8"),
).version;

/**
 * `["<route>", "<title fragment>", "<meta description>"]`.
 *
 * The title fragment is what `titleTemplate` renders as `<fragment> — ArchLang`, so
 * it does not repeat the brand — except on `/`, whose row IS the whole title (that
 * page sets `titleTemplate: false` below, because the home title is fixed wording).
 */
const PAGE_META = [
  [
    "/",
    "ArchLang — floor plans as code, compiled to SVG, DXF and PDF",
    "ArchLang is an open-source (MIT) language for floor plans: write .arch source and compile it to SVG, DXF or PDF, with linting and geometric checks.",
  ],
  [
    "/guide",
    "Guide: floor plans as code",
    "A guided introduction to ArchLang: millimetre coordinates, rooms, walls and openings, expand-time scripting, and how one source file becomes a drawing.",
  ],
  [
    "/examples",
    "Examples: live floor plans",
    "Every plan in the ArchLang repository, live and editable in the browser: houses, large public buildings, and the drawings that each prove one language feature.",
  ],
  [
    "/agents",
    "Floor plans from an AI agent",
    "How an AI agent drives ArchLang end to end from the CLI: one context bundle, JSON output, exit codes, and checking a plan against a brief without an image.",
  ],
  [
    "/relational",
    "Relational placement",
    "Place a room relative to another with right-of, left-of, above or below. ArchLang resolves the absolute coordinates by arithmetic, in dependency order.",
  ],
  [
    "/reference",
    "Language reference",
    "The complete ArchLang language reference: every statement, clause and unit, the scripting forms, the CAD output layers, and the SVG, DXF, PDF and PNG exports.",
  ],
  [
    "/showcase",
    "Showcase: compiled floor plans",
    "Floor plans compiled, not drawn. Each drawing here is a few dozen lines of ArchLang source you can open in the playground and recompile in your browser.",
  ],
  [
    "/cli",
    "CLI reference",
    "Every arch command, flag, export format and exit code, generated from the same capability manifest the CLI itself serves, so this page cannot fall behind it.",
  ],
  [
    "/furniture",
    "Furniture and fixtures",
    "The furniture statement places a catalogued fixture and draws a real plan symbol. Covers the placement modes, the symbol catalogue, sizing and orientation.",
  ],
  [
    "/analysis",
    "Analysis: describe and lint",
    "describe() and lint() read a compiled plan back as facts: rooms, areas, adjacency, what each door connects, an access graph, circulation distances and warnings.",
  ],
  [
    "/axonometric",
    "The axonometric view",
    "arch compile --view iso draws the building instead of the plan: extruded walls with their openings cut. It is an illustration, so it measures nothing.",
  ],
  [
    "/intent",
    "The intent contract",
    "Write a brief down as data, then check a plan against it. arch validate --intent reports code by code which expectations the drawing meets, with no image.",
  ],
  [
    "/errors",
    "Error and warning codes",
    "Every ArchLang diagnostic code with its meaning and a worked example. Errors abort rendering, warnings do not, and arch explain prints any code from the CLI.",
  ],
  [
    "/spec",
    "The language in one page",
    "The whole ArchLang language on one page, written for an AI agent's system prompt: the rules that matter, every statement form, and a compilable worked example.",
  ],
  [
    "/adr/",
    "Architecture decision records",
    "Index of ArchLang's architecture decision records: the decisions behind the compiler, each with its context, the decision taken and the trade-offs accepted.",
  ],
  [
    "/adr/0001-handwritten-parser-vs-lezer",
    "ADR 1 — a hand-written parser",
    "Why ArchLang parses with a hand-written recursive-descent parser rather than Lezer or tree-sitter, and what that buys in error recovery and zero dependencies.",
  ],
  [
    "/adr/0002-optional-dep-geometry",
    "ADR 2 — optional, lazy dependencies",
    "Heavy geometry and raster output stay optional and lazily loaded, so the default SVG path installs nothing beyond ArchLang's zero-dependency core.",
  ],
  [
    "/adr/0003-expand-time-scripting",
    "ADR 3 — expand-time scripting",
    "ArchLang scripting expands at compile time: no runtime, no I/O and no clock, which is what makes the same source produce byte-identical output every time.",
  ],
  [
    "/adr/0004-relational-placement-not-optimizer",
    "ADR 4 — relational placement",
    "Relational placement in ArchLang is deterministic arithmetic resolved in dependency order, not an optimizer, so a plan's coordinates stay predictable.",
  ],
  [
    "/adr/0005-no-invisible-architect",
    "ADR 5 — facts, not an invisible architect",
    "Design intelligence in ArchLang is reported facts plus advisory lint warnings. The compiler never silently rearranges a plan on the author's behalf.",
  ],
  [
    "/adr/0006-solver-as-explicit-transform",
    "ADR 6 — a solver as an explicit transform",
    "A solver in ArchLang is an explicit source-to-source transform you run and read, never invisible behaviour applied while a drawing is being rendered.",
  ],
  [
    "/adr/0007-opt-in-source-annotation",
    "ADR 7 — opt-in source annotation",
    "Editor metadata such as data-span enters ArchLang's SVG output under an opt-in flag, so the default drawing bytes stay identical for every consumer.",
  ],
  [
    "/adr/0008-circulation-as-facts",
    "ADR 8 — circulation as facts",
    "ArchLang reports circulation as facts measured on a clearance-eroded navigation grid: how far you walk and where the pinch is. It generates no layout.",
  ],
  [
    "/adr/0009-ai-first-context-and-distribution",
    "ADR 9 — AI-first context and distribution",
    "ArchLang's AI-first design: one bundled context artifact, error rendering that stays opt-in, and distribution through the CLI rather than through a protocol.",
  ],
  [
    "/adr/0010-compile-boundary-design-system",
    "ADR 10 — the Compile Boundary design system",
    "The Compile Boundary design system: one two-world visual language, a source side and a sheet side, shared by the ArchLang docs site and the playground.",
  ],
  [
    "/adr/0011-machine-applicable-fixes",
    "ADR 11 — machine-applicable fixes",
    "Machine-applicable fixes follow the rustc model: each diagnostic carries an edit a tool can apply, kept distinct from ArchLang's geometric repairer.",
  ],
  [
    "/adr/0012-mcp-shim-discoverability",
    "ADR 12 — an MCP shim for discoverability",
    "An optional stdio MCP shim gives MCP-native hosts a way to reach ArchLang, amending the distribution-over-protocol decision while the CLI stays primary.",
  ],
  [
    "/adr/0013-repair-trajectory-dataset",
    "ADR 13 — the repair-trajectory dataset",
    "ArchLang's repair-trajectory dataset is versioned, fully synthetic and self-verifying, with a contamination guard that keeps the eval corpus out of it.",
  ],
  [
    "/adr/0014-one-light-world",
    "ADR 14 — one light world",
    "Both ArchLang sites are one light world: no dark mode and no dark surface. The two worlds differ by temperature and texture rather than by darkness.",
  ],
  [
    "/adr/0015-cli-as-agent-interface",
    "ADR 15 — the CLI as an agent interface",
    "The ArchLang CLI is an agent interface: one manifest behind every help screen, display filters that never change an exit code, and loud errors on misuse.",
  ],
  [
    "/adr/0016-component-instances-and-frames",
    "ADR 16 — component instances and frames",
    "A placed component resolves in its own frame and is then transformed into plan coordinates, so every derived rule keeps its meaning after a turn or a mirror.",
  ],
  [
    "/adr/0017-fixture-semantics-three-flags",
    "ADR 17 — fixture semantics in three flags",
    "Fixture semantics in ArchLang rest on three distinct flags and one shared predicate, derived from a single table, so the lint rules cannot disagree.",
  ],
  [
    "/adr/0018-zero-dep-wall-joinery",
    "ADR 18 — zero-dependency wall joinery",
    "Every ArchLang wall is joined in one closed-form, zero-dependency pass: split at each crossing, classify by probing, then chain into canonical loops.",
  ],
  [
    "/adr/0019-cloudflare-workers-hosting",
    "ADR 19 — hosting on Cloudflare Workers",
    "Both ArchLang sites are served as Cloudflare Workers static assets and deployed from CI, with no URL change from the hosting move and no server to run.",
  ],
] as const;

type PageMeta = { readonly title: string; readonly description: string };

const PAGE_META_BY_ROUTE: ReadonlyMap<string, PageMeta> = new Map(
  PAGE_META.map(([route, title, description]) => [route, { title, description }]),
);

/**
 * A page source path (`index.md`, `reference.md`, `adr/0001-….md`) → its served
 * route. `cleanUrls` is on, so no `.html` anywhere, and an `index.md` keeps its
 * trailing slash (`/`, `/adr/`) — which is what the canonical URL must carry.
 */
function routeOf(pagePath: string): string {
  const noExt = pagePath.replace(/\.md$/, "");
  const clean = noExt === "index" ? "" : noExt.endsWith("/index") ? noExt.slice(0, -"index".length) : noExt;
  return `/${clean}`;
}

/**
 * The routes that ALSO serve raw markdown at `<route>.md` — derived from what
 * sync-docs.mjs actually dropped into `public/`, never from a second copy of its
 * PAGES table. An empty set (no sync yet) simply omits the `rel=alternate` links.
 */
const RAW_MARKDOWN_ROUTES: ReadonlySet<string> = (() => {
  try {
    const dir = fileURLToPath(new URL("../public", import.meta.url));
    return new Set(
      readdirSync(dir)
        .filter((f) => f.endsWith(".md"))
        .map((f) => `/${f.slice(0, -".md".length)}`),
    );
  } catch {
    return new Set<string>();
  }
})();

/**
 * `<route> → ISO date` for the pages sync-docs GENERATES, written by sync-docs.mjs
 * from `git log` over each page's canonical SOURCE. VitePress derives `lastmod`
 * from the built page's own git history, and these pages are untracked build
 * output — so without this map every generated route ships a sitemap entry with no
 * date at all. Missing file → no stamps, never a failed build.
 */
const LASTMOD: Readonly<Record<string, string>> = (() => {
  try {
    return JSON.parse(readFileSync(fileURLToPath(new URL("./lastmod.json", import.meta.url)), "utf8"));
  } catch {
    return {};
  }
})();

/** JSON-LD for one route, as the `<script type="application/ld+json">` body. */
function structuredData(route: string, url: string, title: string, description: string): string {
  const person = {
    "@type": "Person",
    "@id": `${SITE_ORIGIN}/#author`,
    name: AUTHOR.name,
    url: AUTHOR.url,
    sameAs: [AUTHOR.url],
  };
  const website = {
    "@type": "WebSite",
    "@id": `${SITE_ORIGIN}/#website`,
    url: `${SITE_ORIGIN}/`,
    name: "ArchLang",
    inLanguage: "en-GB",
    publisher: { "@id": `${SITE_ORIGIN}/#author` },
  };
  const graph =
    route === "/"
      ? [
          website,
          person,
          {
            "@type": "SoftwareApplication",
            "@id": `${SITE_ORIGIN}/#software`,
            name: "ArchLang",
            applicationCategory: "DeveloperApplication",
            operatingSystem: "Any",
            softwareVersion: CORE_VERSION,
            url: `${SITE_ORIGIN}/`,
            description,
            license: MIT_LICENSE,
            offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
            author: { "@id": `${SITE_ORIGIN}/#author` },
            publisher: { "@id": `${SITE_ORIGIN}/#author` },
          },
          {
            "@type": "SoftwareSourceCode",
            "@id": `${SITE_ORIGIN}/#source`,
            name: "ArchLang",
            codeRepository: REPO_URL,
            programmingLanguage: "TypeScript",
            license: MIT_LICENSE,
            author: { "@id": `${SITE_ORIGIN}/#author` },
            targetProduct: { "@id": `${SITE_ORIGIN}/#software` },
          },
        ]
      : [
          {
            "@type": "TechArticle",
            "@id": `${url}#article`,
            headline: title,
            name: title,
            description,
            url,
            inLanguage: "en-GB",
            isPartOf: { "@id": `${SITE_ORIGIN}/#website` },
            author: { "@type": "Person", name: AUTHOR.name, url: AUTHOR.url },
            publisher: { "@type": "Person", name: AUTHOR.name, url: AUTHOR.url },
          },
          {
            "@type": "BreadcrumbList",
            "@id": `${url}#breadcrumbs`,
            itemListElement: [
              { "@type": "ListItem", position: 1, name: "ArchLang", item: `${SITE_ORIGIN}/` },
              ...(route.startsWith("/adr/") && route !== "/adr/"
                ? [
                    {
                      "@type": "ListItem",
                      position: 2,
                      name: "Architecture decision records",
                      item: `${SITE_ORIGIN}/adr/`,
                    },
                    { "@type": "ListItem", position: 3, name: title, item: url },
                  ]
                : [{ "@type": "ListItem", position: 2, name: title, item: url }]),
            ],
          },
        ];
  // `</script>` can never appear in these values today, but a JSON-LD body is raw
  // innerHTML — escape the one character that could ever close the tag early.
  return JSON.stringify({ "@context": "https://schema.org", "@graph": graph }).replace(/</g, "\\u003c");
}

// ArchLang docs site (T6.1). Static, isomorphic — no backend. Pages re-use the
// canonical docs maintained in the repo root (language reference, error catalog)
// so the site never drifts from the source of truth.
export default defineConfig({
  title: "ArchLang",
  description:
    "A small declarative language that compiles to professional SVG floor plans — like Typst/LaTeX, but for architecture.",
  // Declared so the crawler, the screen reader and the hyphenation engine all agree.
  lang: "en-GB",
  // `<title>` per page = "<PAGE_META title> — ArchLang". `/` opts out (titleTemplate:
  // false in transformPageData) because its title is fixed wording, brand included.
  titleTemplate: ":title — ArchLang",
  // The site is LIGHT-ONLY (ADR 0014): no appearance toggle, no .dark class, no
  // dark surface anywhere. VitePress's toggle + its localStorage/prefers-color-scheme
  // script are switched off here, so `.dark` never lands on <html>.
  appearance: false,
  // Brand: the ArchLang A-frame-floor-plan favicon (SVG, scales), an apple-touch
  // icon, the paper theme-colour, and an OG/Twitter social card (the 1200×630 wordmark
  // banner). All assets live in public/brand/ — see brand/README.md for the geometry law.
  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/brand/archlang-icon-plum.svg" }],
    ["link", { rel: "alternate icon", href: "/brand/archlang-favicon-32.png", sizes: "32x32" }],
    ["link", { rel: "apple-touch-icon", href: "/brand/archlang-apple-touch.png" }],
    ["meta", { name: "theme-color", content: "#f5f2ea" }],
    // Declare the page light-only. The real opt-out from Chromium's Auto Dark Mode is
    // the CSS `color-scheme: only light` in theme/style.css's :root; this meta just
    // states the same intent for UAs that read it first.
    ["meta", { name: "color-scheme", content: "light" }],
    ["meta", { property: "og:type", content: "website" }],
    // og:title / og:description / twitter:title / twitter:description are DELIBERATELY
    // absent here: transformHead emits them per page from PAGE_META. A static pair in
    // this list would describe all 34 routes identically, which is what it used to do.
    ["meta", { property: "og:image", content: OG_IMAGE }],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    ["meta", { name: "twitter:image", content: OG_IMAGE }],
  ],
  // Per-page title + description, from the PAGE_META table above. Frontmatter always
  // wins, and an unlisted route (the 404) is left exactly as it was.
  transformPageData(pageData) {
    const route = routeOf(pageData.relativePath);
    const meta = PAGE_META_BY_ROUTE.get(route);
    if (!meta) return;
    const patch: Record<string, unknown> = {};
    if (!pageData.frontmatter.description) patch.description = meta.description;
    if (!pageData.frontmatter.title) {
      patch.title = meta.title;
      // The home row IS the whole <title>, brand included — appending the template
      // to it would read "… — ArchLang — ArchLang".
      if (route === "/") patch.titleTemplate = false;
    }
    return patch;
  },
  // Canonical, per-page social cards, the machine-readable alternates and JSON-LD.
  // This hook runs once per page at BUILD time and an exception here fails the build
  // with no page context — so the lookup falls back to the site defaults (return [])
  // rather than throwing on a route the table does not know.
  transformHead({ page, title, description }): HeadConfig[] {
    const route = routeOf(page);
    const meta = PAGE_META_BY_ROUTE.get(route);
    if (!meta) return [];
    const url = SITE_ORIGIN + route;
    const head: HeadConfig[] = [
      ["link", { rel: "canonical", href: url }],
      // Emitted here rather than left to VitePress's own default tag, which
      // interpolates the description into the template UNESCAPED.
      ["meta", { name: "description", content: description }],
      ["meta", { property: "og:url", content: url }],
      ["meta", { property: "og:site_name", content: "ArchLang" }],
      ["meta", { property: "og:title", content: title }],
      ["meta", { property: "og:description", content: description }],
      ["meta", { property: "og:image:width", content: "1200" }],
      ["meta", { property: "og:image:height", content: "630" }],
      ["meta", { property: "og:image:alt", content: "ArchLang — floor plans as code" }],
      ["meta", { name: "twitter:title", content: title }],
      ["meta", { name: "twitter:description", content: description }],
      ["link", { rel: "alternate", type: "text/plain", title: "llms.txt", href: `${SITE_ORIGIN}/llms.txt` }],
    ];
    // The append-`.md` convention llms.txt advertises, stated in the page's own head.
    if (RAW_MARKDOWN_ROUTES.has(route)) {
      head.push(["link", { rel: "alternate", type: "text/markdown", href: `${url}.md` }]);
    }
    // The structured headline is the page's own name, without the " — ArchLang" the
    // <title> carries: a breadcrumb crumb reading "Language reference — ArchLang"
    // inside a trail that already starts at ArchLang says the brand twice.
    head.push(["script", { type: "application/ld+json" }, structuredData(route, url, meta.title, description)]);
    return head;
  },
  // Could be built into a subdir under any static host; "./" keeps asset URLs
  // relative so it works under any base path. (Today it is served at the apex by
  // the archlang-docs Cloudflare Worker — see docs/hosting-and-domains.md.)
  base: "/",
  cleanUrls: true,
  lastUpdated: true,
  // Now that the site has a stable custom domain, emit a sitemap.xml so search
  // engines index the canonical archlang.uk URLs (not the old *.vercel.app host).
  sitemap: {
    hostname: SITE_ORIGIN,
    // VitePress dates each entry from the BUILT page's git history. The nine synced
    // pages and every ADR copy are untracked build output, so they arrived with no
    // date; LASTMOD carries their canonical source's commit date instead. A route
    // VitePress already dated is left alone.
    transformItems: (items) =>
      items.map((item) => {
        const stamped = LASTMOD[`/${item.url}`];
        return stamped && !item.lastmod ? { ...item, lastmod: stamped } : item;
      }),
  },
  // sync-docs.mjs drops a RAW markdown copy of each generated page into public/
  // (served verbatim at `/<route>.md` — the append-`.md` convention llms.txt
  // advertises). Those copies are static assets, not pages: exclude them from
  // markdown page parsing so VitePress neither routes them nor dead-link-checks
  // their canonical relative links (which resolve on the real page, not the copy).
  srcExclude: ["public/**"],
  // The reference/errors pages are synced verbatim from the canonical repo docs,
  // which contain relative links to repo files (examples/*.arch, playground/,
  // CHANGELOG.md, SKILL.md, error-codes.md → the site's /errors page) that are
  // valid on GitHub but not pages on this site under the same name. Don't fail
  // the build on them.
  ignoreDeadLinks: [
    /\.\.\/(examples|playground)\//,
    /\.\.\/\.\.\//,
    /\.\.\/(CHANGELOG|SKILL)/,
    /error-codes/,
    /language-reference/,
    // Machine-readable artifacts served verbatim from public/ (sync-docs.mjs). VitePress
    // knows .txt/.json are assets, but not the unknown .gbnf extension — it takes
    // /archlang.gbnf for a page route and calls it dead. It is a real, served file.
    /^\/archlang\.gbnf$/,
  ],
  // Register the ArchLang grammar with Shiki under the `arch` fence id (the
  // grammar's own `name` is "ArchLang"; its scopeName stays `source.arch`). The
  // `archlang` alias is accepted too.
  markdown: {
    languages: [{ ...archGrammar, name: "arch", aliases: ["archlang"] }],
    theme: archlangLight,
    // Auto-live `arch` fences (T3.1). Like mermaid's docs, every plain ```arch
    // fenced block in a page becomes a live, editable <ArchLive> widget rather
    // than a static highlighted block — with the original Shiki-highlighted
    // <pre> kept as the SSR / no-JS fallback (ArchLive swaps to the editor on
    // mount). This only rewrites fence tokens, so pages that already write an
    // explicit <ArchLive> tag are untouched (no double render).
    //
    // Escape hatch: a fence with an extra `static` info token (```arch static)
    // stays a plain highlighted block. `arch` is still the first info token so
    // Shiki highlights it as ArchLang either way.
    config(md) {
      const defaultFence = md.renderer.rules.fence!;
      md.renderer.rules.fence = (tokens, idx, options, env, self) => {
        // markdown-it only ever calls a fence rule with an in-range `idx`; the `!`
        // states that invariant for `noUncheckedIndexedAccess`.
        const token = tokens[idx]!;
        const info = token.info.trim();
        const attrs = info.split(/\s+/).slice(1); // tokens after the language
        const lang = info.split(/\s+/)[0];
        const highlighted = defaultFence(tokens, idx, options, env, self);
        if (lang !== "arch" || attrs.includes("static")) return highlighted;
        // base64(UTF-8) sidesteps HTML-attribute + Vue-mustache escaping of the
        // multi-line source; ArchLive decodes it. The fallback <pre> is wrapped
        // in v-pre so Vue never interpolates the raw Shiki markup.
        const b64 = Buffer.from(token.content, "utf8").toString("base64");
        return `<ArchLive b64="${b64}">\n<template #fallback><div v-pre>${highlighted}</div></template>\n</ArchLive>\n`;
      };
    },
  },
  // Let theme components (ArchLive) import the built core directly, so docs
  // examples compile client-side — the same alias the playground uses. The core
  // is built before the site (`npm run docs:build` builds the core first), so
  // dist/ exists.
  // The optional Node-only backends are reached only via lazy import()s that never
  // run in the browser — exclude them from prebundling so esbuild doesn't choke on
  // native binaries.
  vite: {
    resolve: {
      alias: {
        archlang: fileURLToPath(new URL("../../dist/index.js", import.meta.url)),
      },
    },
    server: { fs: { allow: [resolve(fileURLToPath(new URL("../..", import.meta.url)))] } },
    optimizeDeps: { exclude: ["@resvg/resvg-js", "pdfkit", "clipper2-wasm", "archlang"] },
    build: { rollupOptions: { external: [/^node:/, "@resvg/resvg-js", "pdfkit", "clipper2-wasm"] } },
  },
  themeConfig: {
    // The ArchLang spark mark beside the "ArchLang" site title in the nav bar.
    // The plum mark reads on both the light docs chrome and the dark mobile nav.
    logo: "/brand/archlang-icon-plum.svg",
    // Calm, grouped top nav: a few primary links plus dropdowns, so the bar
    // stays readable on the home page and every doc page (it's one global nav).
    // Sub-topics live under Reference; the contributor-only ADRs stay in the
    // sidebar (below) rather than the bar. Playground is the standalone CTA — it
    // is intentionally NOT repeated inside Ecosystem.
    nav: [
      { text: "Guide", link: "/guide" },
      {
        text: "Reference",
        items: [
          { text: "Language reference", link: "/reference" },
          { text: "CLI reference", link: "/cli" },
          { text: "Relational placement", link: "/relational" },
          { text: "Furniture & fixtures", link: "/furniture" },
          { text: "Axonometric view", link: "/axonometric" },
          { text: "Analysis: describe & lint", link: "/analysis" },
          { text: "The intent contract", link: "/intent" },
          { text: "Error catalog", link: "/errors" },
        ],
      },
      { text: "Examples", link: "/examples" },
      { text: "Showcase", link: "/showcase" },
      {
        text: "AI Agents",
        items: [
          { text: "Use it from an agent", link: "/agents" },
          { text: "One-page spec", link: "/spec" },
          { text: "CLI reference", link: "/cli" },
        ],
      },
      // Keep one-click reach to the playground… (VitePress appends the external
      // ↗ icon itself for external links, so no manual arrow in the text.)
      { text: "Playground", link: "https://playground.archlang.uk" },
      // …and group the wider brand family (the ArchCanvas product + packages)
      // under an Ecosystem dropdown so docs ↔ archcanvas ↔ packages all link.
      {
        text: "Ecosystem",
        items: [
          { text: "ArchCanvas", link: "https://archcanvas.uk" },
          { text: "npm", link: "https://www.npmjs.com/package/@chanmeng666/archlang" },
          { text: "GitHub", link: "https://github.com/chanmeng666/archlang" },
        ],
      },
    ],
    sidebar: [
      {
        text: "Introduction",
        items: [
          { text: "What is ArchLang?", link: "/guide" },
          { text: "Examples gallery", link: "/examples" },
          { text: "Showcase", link: "/showcase" },
        ],
      },
      {
        text: "For AI agents",
        items: [
          { text: "Use it from an agent", link: "/agents" },
          { text: "One-page spec", link: "/spec" },
        ],
      },
      {
        text: "Language",
        items: [
          { text: "Language reference", link: "/reference" },
          { text: "Relational placement", link: "/relational" },
          { text: "Furniture & fixtures", link: "/furniture" },
          { text: "Axonometric view", link: "/axonometric" },
          { text: "Analysis: describe & lint", link: "/analysis" },
          { text: "The intent contract", link: "/intent" },
          { text: "Error catalog", link: "/errors" },
        ],
      },
      {
        text: "Tooling",
        items: [{ text: "CLI reference", link: "/cli" }],
      },
      {
        // ADRs come from theme/adr-data.js (generated by sync-docs.mjs from docs/adr/).
        // Hand-listing them let the sidebar freeze at 0005 while the directory grew to 0014.
        text: "Design",
        items: [{ text: "Architecture decisions", link: "/adr/" }, ...ADRS],
      },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/chanmeng666/archlang" }],
    search: { provider: "local" },
    // The site-wide footer is rendered by TitleBlockFooter.vue (layout-bottom slot),
    // a drawing title block carrying the project/license/issued cells plus the
    // brand-family ecosystem links. Omitting the built-in `footer` here avoids a
    // duplicate footer.
  },
});
