import { defineConfig } from "vitepress";
// Generated by sync-docs.mjs (which the dev/build npm scripts run first) from docs/adr/.
import { ADRS } from "./theme/adr-data.js";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

// The ArchLang TextMate grammar — generated from the single source of truth
// (scripts/gen-grammars.ts → editors/archlang.tmLanguage.json, the same grammar
// VS Code uses). Loading it here lets Shiki highlight `arch` fenced code blocks
// instead of falling back to plain text, and keeps the site in lockstep with the
// grammar (regenerate the grammar → the site picks it up; nothing to hand-sync).
const archGrammar = JSON.parse(
  readFileSync(fileURLToPath(new URL("../../editors/archlang.tmLanguage.json", import.meta.url)), "utf8"),
);

// The one light source-world syntax palette (ADR 0014). Same eight hexes as the
// `--syn-*` tokens in theme/style.css and the fallbacks in scripts/gen-grammars.ts
// — all ≥4.5:1 on the code-fence grounds (--src-bg #eceef2 / --src-surface #fbfbfc).
// A SINGLE theme (not a {light,dark} pair) makes Shiki emit plain `color:#hex`
// with no --shiki-* vars to swap. Neither stock light theme was usable: github-light's
// comment (#6e7781) is 4.40:1 on our grounds, and github-light-high-contrast's keyword
// is red — which would collide with "redline means attention only".
const archlangLight = {
  name: "archlang-light",
  type: "light" as const,
  colors: { "editor.background": "#eceef2", "editor.foreground": "#1a1d23" },
  tokenColors: [
    { scope: ["comment", "punctuation.definition.comment"], settings: { foreground: "#5a616e", fontStyle: "italic" } },
    { scope: ["string", "constant.other.symbol"], settings: { foreground: "#8a5a00" } },
    { scope: ["constant.numeric", "constant.language.boolean"], settings: { foreground: "#0f6f7a" } },
    { scope: ["constant.language", "constant.character", "variable.language"], settings: { foreground: "#0b57d0" } },
    { scope: ["keyword", "storage.modifier"], settings: { foreground: "#6b3ae0", fontStyle: "bold" } },
    {
      scope: ["storage.type", "entity.name.type", "entity.name.class", "support.type", "support.class"],
      settings: { foreground: "#9a4a06", fontStyle: "bold" },
    },
    {
      scope: ["entity.name.function", "support.function", "entity.name.tag", "variable.other.property"],
      settings: { foreground: "#14602a" },
    },
    { scope: ["keyword.operator", "punctuation"], settings: { foreground: "#464d59" } },
    { scope: ["variable", "entity.name", "meta.definition.variable"], settings: { foreground: "#1a1d23" } },
  ],
};

// ArchLang docs site (T6.1). Static, isomorphic — no backend. Pages re-use the
// canonical docs maintained in the repo root (language reference, error catalog)
// so the site never drifts from the source of truth.
export default defineConfig({
  title: "ArchLang",
  description:
    "A small declarative language that compiles to professional SVG floor plans — like Typst/LaTeX, but for architecture.",
  // The site is LIGHT-ONLY (ADR 0014): no appearance toggle, no .dark class, no
  // dark surface anywhere. VitePress's toggle + its localStorage/prefers-color-scheme
  // script are switched off here, so `.dark` never lands on <html>.
  appearance: false,
  // Brand: the ArchLang A-frame-floor-plan favicon (SVG, scales), an apple-touch
  // icon, the paper theme-colour, and an OG/Twitter social card (the 1200×630 wordmark
  // banner). All assets live in public/brand/ — see brand/README.md for the geometry law.
  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/brand/archlang-icon-plum.svg" }],
    ["link", { rel: "alternate icon", href: "/brand/archlang-favicon-32.png", sizes: "32x32" }],
    ["link", { rel: "apple-touch-icon", href: "/brand/archlang-apple-touch.png" }],
    ["meta", { name: "theme-color", content: "#f5f2ea" }],
    // Declare the page light-only. The real opt-out from Chromium's Auto Dark Mode is
    // the CSS `color-scheme: only light` in theme/style.css's :root; this meta just
    // states the same intent for UAs that read it first.
    ["meta", { name: "color-scheme", content: "light" }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:title", content: "ArchLang — code to floor plans" }],
    [
      "meta",
      {
        property: "og:description",
        content:
          "A declarative language that compiles to professional SVG floor plans — like Typst/LaTeX, but for architecture.",
      },
    ],
    ["meta", { property: "og:image", content: "https://archlang.uk/brand/archlang-og.png" }],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    ["meta", { name: "twitter:image", content: "https://archlang.uk/brand/archlang-og.png" }],
  ],
  // Built into a subdir under the eventual GitHub Pages / Vercel project; "./"
  // keeps asset URLs relative so it works under any base path.
  base: "/",
  cleanUrls: true,
  lastUpdated: true,
  // Now that the site has a stable custom domain, emit a sitemap.xml so search
  // engines index the canonical archlang.uk URLs (not the old *.vercel.app host).
  sitemap: { hostname: "https://archlang.uk" },
  // sync-docs.mjs drops a RAW markdown copy of each generated page into public/
  // (served verbatim at `/<route>.md` — the append-`.md` convention llms.txt
  // advertises). Those copies are static assets, not pages: exclude them from
  // markdown page parsing so VitePress neither routes them nor dead-link-checks
  // their canonical relative links (which resolve on the real page, not the copy).
  srcExclude: ["public/**"],
  // The reference/errors pages are synced verbatim from the canonical repo docs,
  // which contain relative links to repo files (examples/*.arch, playground/,
  // CHANGELOG.md, SKILL.md, error-codes.md → the site's /errors page) that are
  // valid on GitHub but not pages on this site under the same name. Don't fail
  // the build on them.
  ignoreDeadLinks: [
    /\.\.\/(examples|playground)\//,
    /\.\.\/\.\.\//,
    /\.\.\/(CHANGELOG|SKILL)/,
    /error-codes/,
    /language-reference/,
    // Machine-readable artifacts served verbatim from public/ (sync-docs.mjs). VitePress
    // knows .txt/.json are assets, but not the unknown .gbnf extension — it takes
    // /archlang.gbnf for a page route and calls it dead. It is a real, served file.
    /^\/archlang\.gbnf$/,
  ],
  // Register the ArchLang grammar with Shiki under the `arch` fence id (the
  // grammar's own `name` is "ArchLang"; its scopeName stays `source.arch`). The
  // `archlang` alias is accepted too.
  markdown: {
    languages: [{ ...archGrammar, name: "arch", aliases: ["archlang"] }],
    theme: archlangLight,
    // Auto-live `arch` fences (T3.1). Like mermaid's docs, every plain ```arch
    // fenced block in a page becomes a live, editable <ArchLive> widget rather
    // than a static highlighted block — with the original Shiki-highlighted
    // <pre> kept as the SSR / no-JS fallback (ArchLive swaps to the editor on
    // mount). This only rewrites fence tokens, so pages that already write an
    // explicit <ArchLive> tag are untouched (no double render).
    //
    // Escape hatch: a fence with an extra `static` info token (```arch static)
    // stays a plain highlighted block. `arch` is still the first info token so
    // Shiki highlights it as ArchLang either way.
    config(md) {
      const defaultFence = md.renderer.rules.fence!;
      md.renderer.rules.fence = (tokens, idx, options, env, self) => {
        const token = tokens[idx];
        const info = token.info.trim();
        const attrs = info.split(/\s+/).slice(1); // tokens after the language
        const lang = info.split(/\s+/)[0];
        const highlighted = defaultFence(tokens, idx, options, env, self);
        if (lang !== "arch" || attrs.includes("static")) return highlighted;
        // base64(UTF-8) sidesteps HTML-attribute + Vue-mustache escaping of the
        // multi-line source; ArchLive decodes it. The fallback <pre> is wrapped
        // in v-pre so Vue never interpolates the raw Shiki markup.
        const b64 = Buffer.from(token.content, "utf8").toString("base64");
        return `<ArchLive b64="${b64}">\n<template #fallback><div v-pre>${highlighted}</div></template>\n</ArchLive>\n`;
      };
    },
  },
  // Let theme components (ArchLive) import the built core directly, so docs
  // examples compile client-side — the same alias the playground uses. The core
  // is built before the site (see vercel.json → docs:build), so dist/ exists.
  // The optional Node-only backends are reached only via lazy import()s that never
  // run in the browser — exclude them from prebundling so esbuild doesn't choke on
  // native binaries.
  vite: {
    resolve: {
      alias: {
        archlang: fileURLToPath(new URL("../../dist/index.js", import.meta.url)),
      },
    },
    server: { fs: { allow: [resolve(fileURLToPath(new URL("../..", import.meta.url)))] } },
    optimizeDeps: { exclude: ["@resvg/resvg-js", "pdfkit", "clipper2-wasm", "archlang"] },
    build: { rollupOptions: { external: [/^node:/, "@resvg/resvg-js", "pdfkit", "clipper2-wasm"] } },
  },
  themeConfig: {
    // The ArchLang spark mark beside the "ArchLang" site title in the nav bar.
    // The plum mark reads on both the light docs chrome and the dark mobile nav.
    logo: "/brand/archlang-icon-plum.svg",
    // Calm, grouped top nav: a few primary links plus dropdowns, so the bar
    // stays readable on the home page and every doc page (it's one global nav).
    // Sub-topics live under Reference; the contributor-only ADRs stay in the
    // sidebar (below) rather than the bar. Playground is the standalone CTA — it
    // is intentionally NOT repeated inside Ecosystem.
    nav: [
      { text: "Guide", link: "/guide" },
      {
        text: "Reference",
        items: [
          { text: "Language reference", link: "/reference" },
          { text: "CLI reference", link: "/cli" },
          { text: "Relational placement", link: "/relational" },
          { text: "Furniture & fixtures", link: "/furniture" },
          { text: "Analysis: describe & lint", link: "/analysis" },
          { text: "The intent contract", link: "/intent" },
          { text: "Error catalog", link: "/errors" },
        ],
      },
      { text: "Examples", link: "/examples" },
      {
        text: "AI Agents",
        items: [
          { text: "Use it from an agent", link: "/agents" },
          { text: "One-page spec", link: "/spec" },
          { text: "CLI reference", link: "/cli" },
        ],
      },
      // Keep one-click reach to the playground… (VitePress appends the external
      // ↗ icon itself for external links, so no manual arrow in the text.)
      { text: "Playground", link: "https://playground.archlang.uk" },
      // …and group the wider brand family (the ArchCanvas product + packages)
      // under an Ecosystem dropdown so docs ↔ archcanvas ↔ packages all link.
      {
        text: "Ecosystem",
        items: [
          { text: "ArchCanvas", link: "https://archcanvas.chanmeng.org" },
          { text: "npm", link: "https://www.npmjs.com/package/@chanmeng666/archlang" },
          { text: "GitHub", link: "https://github.com/chanmeng666/archlang" },
        ],
      },
    ],
    sidebar: [
      {
        text: "Introduction",
        items: [
          { text: "What is ArchLang?", link: "/guide" },
          { text: "Examples gallery", link: "/examples" },
        ],
      },
      {
        text: "For AI agents",
        items: [
          { text: "Use it from an agent", link: "/agents" },
          { text: "One-page spec", link: "/spec" },
        ],
      },
      {
        text: "Language",
        items: [
          { text: "Language reference", link: "/reference" },
          { text: "Relational placement", link: "/relational" },
          { text: "Furniture & fixtures", link: "/furniture" },
          { text: "Analysis: describe & lint", link: "/analysis" },
          { text: "The intent contract", link: "/intent" },
          { text: "Error catalog", link: "/errors" },
        ],
      },
      {
        text: "Tooling",
        items: [{ text: "CLI reference", link: "/cli" }],
      },
      {
        // ADRs come from theme/adr-data.js (generated by sync-docs.mjs from docs/adr/).
        // Hand-listing them let the sidebar freeze at 0005 while the directory grew to 0014.
        text: "Design",
        items: [{ text: "Architecture decisions", link: "/adr/" }, ...ADRS],
      },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/chanmeng666/archlang" }],
    search: { provider: "local" },
    // The site-wide footer is rendered by TitleBlockFooter.vue (layout-bottom slot),
    // a drawing title block carrying the project/license/issued cells plus the
    // brand-family ecosystem links. Omitting the built-in `footer` here avoids a
    // duplicate footer.
  },
});
