/**
 * Generate the editor grammars from the one grammar source of truth
 * (`src/grammar/tokens.ts`):
 *   - editors/archlang.tmLanguage.json   (TextMate, for VS Code et al.)
 *   - playground/src/arch-language.js     (CodeMirror 6 StreamLanguage)
 *
 * Run `npm run gen:grammars` after editing a keyword. CI regenerates and asserts
 * no drift (`test/grammar-drift.test.ts`), so the editor grammars can never fall
 * out of sync with the parser. The render functions are pure (no fs) so the
 * drift test can call them in-memory.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { KEYWORDS, OPERATORS, RULES } from "../src/grammar/tokens.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

const escapeRegex = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const alt = (words: readonly string[]): string => words.join("|");

/** The TextMate grammar JSON (string), generated from the token source. */
export function renderTmLanguage(): string {
  const grammar = {
    $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    name: "ArchLang",
    scopeName: "source.arch",
    fileTypes: ["arch"],
    patterns: [
      { include: "#comments" },
      { include: "#strings" },
      { include: "#id-binding" },
      { include: "#component-def" },
      { include: "#numbers" },
      { include: "#keywords" },
      { include: "#constants" },
      { include: "#operators" },
    ],
    repository: {
      comments: { match: RULES.comment, name: "comment.line.number-sign.arch" },
      strings: {
        name: "string.quoted.double.arch",
        begin: '"',
        beginCaptures: { "0": { name: "punctuation.definition.string.begin.arch" } },
        end: '"|(?=$)',
        endCaptures: { "0": { name: "punctuation.definition.string.end.arch" } },
        patterns: [{ match: "\\\\.", name: "constant.character.escape.arch" }],
      },
      "id-binding": {
        match: `\\b(id)\\s*(=)\\s*(${RULES.ident})`,
        captures: {
          "1": { name: "keyword.other.arch" },
          "2": { name: "keyword.operator.assignment.arch" },
          "3": { name: "entity.name.tag.arch" },
        },
      },
      "component-def": {
        match: `\\b(component)\\s+(${RULES.ident})`,
        captures: {
          "1": { name: "keyword.control.arch" },
          "2": { name: "entity.name.function.arch" },
        },
      },
      numbers: {
        patterns: [
          { match: `\\b${RULES.dimension}\\b`, name: "constant.numeric.dimension.arch" },
          { match: `\\b${RULES.number}\\b`, name: "constant.numeric.arch" },
        ],
      },
      keywords: {
        patterns: [
          { match: `\\b(${alt(KEYWORDS.control)})\\b`, name: "keyword.control.arch" },
          { match: `\\b(${alt(KEYWORDS.element)})\\b`, name: "storage.type.element.arch" },
          { match: `\\b(${alt(KEYWORDS.attribute)})\\b`, name: "keyword.other.arch" },
        ],
      },
      constants: { match: `\\b(${alt(KEYWORDS.enum)})\\b`, name: "constant.language.arch" },
      operators: { match: OPERATORS.map(escapeRegex).join("|"), name: "keyword.operator.arch" },
    },
  };
  return JSON.stringify(grammar, null, 2) + "\n";
}

const setLiteral = (words: readonly string[]): string => `new Set([${words.map((w) => `"${w}"`).join(", ")}])`;

/** The playground CodeMirror StreamLanguage (string), generated from the source. */
export function renderPlayground(): string {
  return `/**
 * CodeMirror 6 language support for ArchLang.
 *
 * GENERATED by scripts/gen-grammars.ts from src/grammar/tokens.ts — do not edit
 * by hand. A StreamLanguage tokenizer plus a HighlightStyle and a linter fed by
 * the compiler's own \`diagnostics\` (span byte-offsets map directly to editor
 * positions, since the lexer indexes the source string).
 */
import { StreamLanguage, LanguageSupport, syntaxHighlighting, HighlightStyle } from "@codemirror/language";
import { linter } from "@codemirror/lint";
import { tags as t } from "@lezer/highlight";
import { compile } from "archlang";

const CONTROL = ${setLiteral(KEYWORDS.control)};
const ELEMENT = ${setLiteral(KEYWORDS.element)};
const ATTR = ${setLiteral(KEYWORDS.attribute)};
const ENUM = ${setLiteral(KEYWORDS.enum)};

const archStream = StreamLanguage.define({
  name: "arch",
  languageData: { commentTokens: { line: "#" } },

  token(stream) {
    if (stream.eatSpace()) return null;

    // Comment to end of line.
    if (stream.match(/^#.*/)) return "comment";

    // String literal with \\" / \\\\ escapes (does not span lines).
    if (stream.peek() === '"') {
      stream.next();
      let escaped = false;
      let ch;
      while ((ch = stream.next()) != null) {
        if (escaped) { escaped = false; continue; }
        if (ch === "\\\\") { escaped = true; continue; }
        if (ch === '"') break;
      }
      return "string";
    }

    // Number, optionally a literal dimension WxH.
    if (stream.match(/^[0-9]+(?:\\.[0-9]+)?(?:x[0-9]+(?:\\.[0-9]+)?)?/)) return "number";
    if (stream.match(/^\\.[0-9]+/)) return "number";

    // Arrow before minus; multi-char operators before single.
    if (stream.match(/^(->|==|!=|<=|>=|&&|\\|\\||\\.\\.)/)) return "operator";
    if (stream.match(/^[+\\-*/%=:,<>!\\[\\]]/)) return "operator";
    if (stream.match(/^[(){}]/)) return "bracket";

    // Identifier / keyword.
    const id = stream.match(/^[A-Za-z_][A-Za-z0-9_]*/);
    if (id) {
      const word = id[0];
      if (CONTROL.has(word)) return "keyword";
      if (ELEMENT.has(word)) return "typeName";
      if (ATTR.has(word)) return "propertyName";
      if (ENUM.has(word)) return "atom";
      return "variableName";
    }

    stream.next();
    return null;
  },
});

// Colours are CSS vars (valid style-mod values) so the shared token block owns
// them (playground/src/styles/tokens.css == docs-site/.vitepress/theme/style.css);
// the fallback hex repeats the same value, each checked ≥4.5:1 on BOTH light source
// grounds (--src-bg #eceef2 and --src-surface #fbfbfc). Change the palette in the
// token block — and mirror it in docs-site/.vitepress/config.ts's Shiki theme — not here.
const highlightStyle = HighlightStyle.define([
  { tag: t.keyword, color: "var(--syn-keyword, #6b3ae0)", fontWeight: "600" },
  { tag: t.typeName, color: "var(--syn-typename, #9a4a06)", fontWeight: "600" },
  { tag: t.propertyName, color: "var(--syn-propertyname, #14602a)" },
  { tag: t.atom, color: "var(--syn-atom, #0b57d0)" },
  { tag: t.number, color: "var(--syn-number, #0f6f7a)" },
  { tag: t.string, color: "var(--syn-string, #8a5a00)" },
  { tag: t.comment, color: "var(--syn-comment, #5a616e)", fontStyle: "italic" },
  { tag: t.operator, color: "var(--syn-operator, #464d59)" },
]);

export function archLanguage() {
  return new LanguageSupport(archStream, [syntaxHighlighting(highlightStyle)]);
}

/** A CodeMirror linter that surfaces the compiler's diagnostics inline. */
export function archLinter() {
  return linter(
    (view) => {
      const doc = view.state.doc;
      const text = doc.toString();
      const { diagnostics } = compile(text, { noCache: true });
      const len = text.length;
      const out = [];
      for (const d of diagnostics) {
        const from = Math.max(0, Math.min(d.span?.start ?? 0, len));
        const to = Math.max(from, Math.min(d.span?.end ?? from, len));
        out.push({
          from,
          to: to > from ? to : Math.min(from + 1, len),
          severity: d.severity === "error" ? "error" : "warning",
          message: d.code ? \`\${d.message}  [\${d.code}]\` : d.message,
        });
      }
      return out;
    },
    { delay: 250 },
  );
}
`;
}

/** Write both grammars to disk (CLI entry). */
function main(): void {
  writeFileSync(resolve(ROOT, "editors/archlang.tmLanguage.json"), renderTmLanguage());
  writeFileSync(resolve(ROOT, "playground/src/arch-language.js"), renderPlayground());
  process.stdout.write("✓ generated editor grammars from src/grammar/tokens.ts\n");
}

// Run only when invoked directly (not when imported by the drift test).
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
