/**
 * Generate `docs/error-codes.md` from the error catalog (`src/error-catalog.ts`).
 *
 * Run `npm run gen:errors` after editing the catalog. A drift test
 * (`test/explain.test.ts`) regenerates and asserts the committed doc matches, so
 * the reference and the catalog can never diverge.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { ERROR_CATALOG, ERROR_CODES } from "../src/error-catalog.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

/** The full `docs/error-codes.md` content (string), generated from the catalog. */
export function renderErrorCodes(): string {
  const errors = ERROR_CODES.filter((c) => ERROR_CATALOG[c].severity === "error");
  const warnings = ERROR_CODES.filter((c) => ERROR_CATALOG[c].severity === "warning");

  const out: string[] = [
    "<!-- GENERATED by scripts/gen-error-codes.ts from src/error-catalog.ts — do not edit by hand. -->",
    "",
    "# ArchLang error codes",
    "",
    "Every diagnostic carries a stable code. Look one up with `arch explain <CODE>`",
    "(e.g. `arch explain E_ROOM_SIZE`). Errors abort rendering; warnings do not.",
    "",
    `**${errors.length} errors** · **${warnings.length} warnings**`,
    "",
    "| Code | Severity | Summary |",
    "| --- | --- | --- |",
    ...ERROR_CODES.map((c) => `| [\`${c}\`](#${c.toLowerCase()}) | ${ERROR_CATALOG[c].severity} | ${ERROR_CATALOG[c].message} |`),
    "",
  ];

  for (const c of ERROR_CODES) {
    const e = ERROR_CATALOG[c];
    out.push(
      `## ${c}`,
      "",
      `*${e.severity}* — ${e.message}`,
      "",
      `**Cause.** ${e.cause}`,
      "",
      `**Fix.** ${e.fix}`,
      "",
      "```arch",
      e.example,
      "```",
      "",
    );
  }
  return out.join("\n").replace(/\n+$/, "\n");
}

function main(): void {
  writeFileSync(resolve(ROOT, "docs/error-codes.md"), renderErrorCodes());
  process.stdout.write("✓ generated docs/error-codes.md from src/error-catalog.ts\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
