/**
 * Generate `paper/facts.json` + `paper/facts.tex` — every STRUCTURAL number the
 * papers in `paper/` cite, derived from the same sources of truth the compiler
 * itself uses (`src/grammar/tokens.ts`, `src/error-catalog.ts`,
 * `src/lint/rules/index.ts`, `src/manifest.ts`) rather than retyped into prose.
 *
 * WHY THIS EXISTS, and why it is drift-gated like every other generator: the
 * papers' central claim is that a description of a system, hand-typed beside the
 * system, drifts from it silently — and that the remedy is to DERIVE the
 * description instead. A paper about that claim which retypes "115 error codes"
 * into LaTeX would be the defect it documents. So every count below is
 * interpolated from its owner, `check:drift` fails when one moves, and the
 * `.tex` is the only thing the papers are allowed to cite.
 *
 * DELIBERATELY EXCLUDED — scale and provenance facts (LOC, commit count, test
 * counts, npm downloads, eval rates). Those move on every commit, so gating them
 * here would fail `check:drift` on unrelated work and train people to regenerate
 * blindly, which is exactly the reflex the papers argue against. They live in
 * `paper/scale-snapshot.json` (written by `scripts/snapshot-paper-scale.ts` with
 * an explicit `--date`, NOT drift-gated) and in `paper/facts-manual.tex`, where
 * each carries a source and a measurement date.
 *
 * {@link renderFacts} is pure (no fs, no clock) so a drift test can regenerate it
 * in memory. Run `npm run gen:paper-facts`; CI asserts no drift.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ERROR_CATALOG } from "../src/error-catalog.js";
import { DOOR_KINDS, KEYWORDS, OPERATORS } from "../src/grammar/tokens.js";
import { LINT_RULES } from "../src/lint/rules/index.js";
import { EXPORT_FORMATS, buildManifest } from "../src/manifest.js";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const ROOT = resolve(HERE, "..");

/**
 * The version string is deliberately NOT read from `package.json`: a release bump
 * would then drift this artifact for a reason no paper number depends on. The
 * papers cite a version in prose, dated, in `facts-manual.tex`.
 */
const MANIFEST = buildManifest("0.0.0");

/** A LaTeX control sequence must be letters only — map a JSON key onto one. */
function macroName(key: string): string {
  const camel = key.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
  const letters = camel.replace(/[^A-Za-z]/g, "");
  return `fact${letters.charAt(0).toUpperCase()}${letters.slice(1)}`;
}

/** Every structural count, derived from its single source of truth. */
export function facts(): Record<string, number> {
  const codes = Object.keys(ERROR_CATALOG);
  return {
    // Error catalogue — the codes an agent's loop keys off.
    errorCodesTotal: codes.length,
    errorCodesError: codes.filter((c) => c.startsWith("E_")).length,
    errorCodesWarning: codes.filter((c) => c.startsWith("W_")).length,

    // Language surface — one table, four categories.
    keywordsTotal: KEYWORDS.control.length + KEYWORDS.element.length + KEYWORDS.attribute.length + KEYWORDS.enum.length,
    keywordsControl: KEYWORDS.control.length,
    keywordsElement: KEYWORDS.element.length,
    keywordsAttribute: KEYWORDS.attribute.length,
    keywordsEnum: KEYWORDS.enum.length,
    operators: OPERATORS.length,
    doorKinds: DOOR_KINDS.length,

    // Analysis + agent interface.
    lintRules: LINT_RULES.length,
    cliCommands: MANIFEST.commands.length,
    cliFlags: MANIFEST.commands.reduce((n, c) => n + c.flags.length, 0),
    cliExamples: MANIFEST.commands.reduce((n, c) => n + c.examples.length, 0),
    exportFormats: EXPORT_FORMATS.length,
    exportFormatsZeroDep: EXPORT_FORMATS.filter((f) => f.zeroDep).length,
  };
}

/** Deterministic JSON + the LaTeX macro file the papers actually cite. */
export function renderFacts(): { json: string; tex: string } {
  const f = facts();
  const keys = Object.keys(f).sort();
  const json = `${JSON.stringify(Object.fromEntries(keys.map((k) => [k, f[k]])), null, 2)}\n`;
  const tex = [
    "% GENERATED by scripts/gen-paper-facts.ts — do not hand-edit.",
    "% Every number here is derived from the compiler's own source of truth.",
    "% Regenerate with `npm run gen:paper-facts`; `npm run check:drift` gates it.",
    ...keys.map((k) => `\\newcommand{\\${macroName(k)}}{${f[k]}\\xspace}`),
    "",
  ].join("\n");
  return { json, tex };
}

function main(): void {
  const { json, tex } = renderFacts();
  writeFileSync(resolve(ROOT, "paper/facts.json"), json);
  writeFileSync(resolve(ROOT, "paper/facts.tex"), tex);
  process.stdout.write("✓ generated paper/facts.json + paper/facts.tex from the compiler's own tables\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
