/**
 * Generate `spec.llm.md` — the learn-the-whole-language-in-one-prompt spec.
 *
 * This is the single artifact an AI agent ingests (via `arch spec`, or by reading
 * the file) to write valid ArchLang first-try. It is deliberately tiny: the full
 * grammar, the handful of gotchas models trip on, the CLI loop, two complete
 * worked examples, and a common-mistakes table — sized to drop into a system
 * prompt, not the 500-line human reference.
 *
 * Like `scripts/gen-grammars.ts`, the dynamic parts are pulled from the single
 * sources of truth so the spec can never drift: keyword lists come from
 * `src/grammar/tokens.ts`, and the worked examples are the real files under
 * `examples/`. {@link renderLlmSpec} is pure (examples passed in) so the drift
 * test (`test/llm-spec-drift.test.ts`) can regenerate it in-memory. Run
 * `npm run gen:spec` after editing; CI asserts no drift.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { KEYWORDS } from "../src/grammar/tokens.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

/** The example files embedded verbatim, in order. */
export const SPEC_EXAMPLES = ["studio.arch", "parametric.arch"] as const;

/**
 * One-line grammar for each built-in element, keyed by element keyword. Keys MUST
 * match `KEYWORDS.element` exactly — {@link renderLlmSpec} throws otherwise, so a
 * new element can't ship without a spec line (the drift guard).
 */
const ELEMENT_GRAMMAR: Record<string, string> = {
  wall: "wall <category> thickness <mm> [material <name>] { (x,y) (x,y) … [close] }   # category e.g. exterior/partition; `close` makes a loop",
  room: 'room [id=<name>] at (x,y) size <W>x<H> [label "…"] [uses living|kitchen|dining|bedroom|bath|wc|hall|circulation|storage|utility|office|entry …]   # OR relational: room [id=…] (right-of|left-of|below|above) <roomId> [align top|middle|bottom|left|right] [gap <mm>] size <W>x<H> [label "…"]',
  door: "door [id=<name>] at (x,y) width <mm> [wall <id|category>] [hinge left|right] [swing in|out]   # must sit on a wall",
  window: "window [id=<name>] at (x,y) width <mm> [wall <id|category>]   # must sit on a wall",
  opening:
    "opening [id=<name>] at (x,y) width <mm> [wall <id|category>]   # a leaf-less cased opening (gap in a wall) that still connects the two spaces",
  furniture:
    'furniture <category> (at (x,y) | against wall <id> [segment <n>] [offset <mm>] [side left|right]) [size <W>x<H>] [label "…"] [rotate 0|90|180|270] [in <roomId>]   # `at` size is plan W×H; `against` size is wall-relative along×depth and derives position+rotation, with `side` inferred from `in <roomId>` when omitted; a known fixture (wc/basin/shower/bathtub/kitchen_sink/counter/stove/fridge…) `against wall` may omit `size` to use its catalogued footprint',
  dim: 'dim (x,y)->(x,y) offset <mm> [text "…"]   # a dimension line',
  column: "column [id=<name>] at (x,y) size <W>x<H>",
};

const bullet = (items: readonly string[]): string => items.map((k) => `\`${k}\``).join(", ");

/**
 * Render `spec.llm.md` from the token source + the given example file contents
 * (a map of filename → source). Pure: no fs, no clock — safe for the drift test.
 */
export function renderLlmSpec(examples: Record<string, string>): string {
  // Drift guard: every element keyword must have a grammar line, and vice-versa.
  const elementKeys = [...KEYWORDS.element].sort();
  const grammarKeys = Object.keys(ELEMENT_GRAMMAR).sort();
  if (JSON.stringify(elementKeys) !== JSON.stringify(grammarKeys)) {
    throw new Error(
      `ELEMENT_GRAMMAR is out of sync with KEYWORDS.element.\n` +
        `  elements: ${elementKeys.join(", ")}\n  grammar:  ${grammarKeys.join(", ")}`,
    );
  }

  // A fenced block (not a bullet list) so the `<placeholder>` angle brackets are
  // safe everywhere they render (GitHub, npm, and the Vue-compiled docs site).
  const elementLines = "```text\n" + KEYWORDS.element.map((k) => ELEMENT_GRAMMAR[k]).join("\n") + "\n```";

  const exampleBlocks = SPEC_EXAMPLES.map((name) => {
    const src = examples[name];
    if (src === undefined) throw new Error(`missing example "${name}" for spec generation`);
    return `### \`examples/${name}\`\n\n\`\`\`arch\n${src.replace(/\r\n/g, "\n").replace(/\n+$/, "")}\n\`\`\``;
  }).join("\n\n");

  return `<!-- GENERATED by scripts/gen-llm-spec.ts — do not edit by hand. Run \`npm run gen:spec\`. -->

# ArchLang in one prompt

ArchLang is a tiny declarative language that compiles a \`.arch\` source file into a professional
floor-plan drawing (SVG/PNG/PDF/DXF). It is built for AI agents: deterministic (same source →
identical output), pure (no runtime/IO), and self-correcting (every error carries a machine code and
a \`fix\`). This page is everything you need to author it. Print it any time with \`arch spec\`.

## The 7 rules that matter

1. **Units are millimetres.** A 4-metre wall is \`4000\`, not \`4\`.
2. **Origin is top-left; +x goes right, +y goes DOWN** (screen/SVG convention — *not* math y-up).
3. **Coordinates are \`(x, y)\` tuples; sizes are \`WxH\`** (e.g. \`4000x3000\`) or \`<expr> x <expr>\` with spaces.
4. **Doors and windows must lie ON a wall segment** (on its centerline), or you get a
   \`W_DOOR_OFF_WALL\` / \`W_WINDOW_OFF_WALL\` warning.
5. **String interpolation is \`"{expr}"\`** inside double quotes (e.g. \`label "Unit {i}"\`).
6. **Ids must be unique.** Omit \`id=\` to auto-generate one; give an \`id\` only when you reference it.
7. **Everything is expand-time and pure** — \`let\`/\`for\`/\`if\`/functions all evaluate during compile.

## Structure

\`\`\`arch
plan "Title" {
  units mm            # required-ish settings come first
  grid 50             # snap grid in mm
  scale 1:50          # drawing scale (annotation only)
  north up            # up | down | left | right
  # … elements and scripting …
  title { project "…" drawn_by "…" date "…" }
}
\`\`\`

## Elements

${elementLines}

## Scripting (all expand-time, deterministic)

- \`let NAME = expr\` — bind a constant. \`NAME = expr\` — reassign an existing binding.
- \`let f(a, b) = expr\` — a pure value-function. Built-ins: \`min max abs sqrt floor ceil round len str\`.
- \`for i in lo..hi { … }\` — loop over a half-open integer range (\`0..3\` → 0,1,2).
- \`if cond { … } else { … }\` · \`while cond { … }\`.
- \`set <element>(attr: value)\` — scoped default for following elements (e.g. \`set door(swing: out)\`).
- Arrays: \`[a, b, c]\`, indexed \`arr[i]\`. Operators: \`+ - * / %\`, \`== != < > <= >=\`, \`&& ||\`. Comments: \`# …\`.
- \`import "lib/x.arch": name\` and \`component name(args) { … }\` for reuse.

## Keyword reference

- **Settings / control:** ${bullet(KEYWORDS.control)}
- **Elements:** ${bullet(KEYWORDS.element)}
- **Attributes:** ${bullet(KEYWORDS.attribute)}
- **Enums / values:** ${bullet(KEYWORDS.enum)}

## CLI loop (how an agent drives it)

\`\`\`bash
arch spec                              # print this spec
arch manifest --json                   # the whole CLI API as data: commands, flags, formats, lint rules, error codes
arch compile plan.arch -o out.svg --json   # render; JSON has { ok, diagnostics, summary }
echo '<source>' | arch compile - --json    # compile from stdin (no temp file)
arch preview plan.arch -o out.png --json   # render a PNG you can SHOW the user (zero-install where resvg is present; --install fetches it)
arch describe plan.arch --json         # semantic facts: rooms, areas, adjacency, what doors connect
arch lint plan.arch --json             # architectural soundness warnings
arch validate plan.arch --strict --json   # parse + lint, no render; --strict fails on warnings too
arch explain E_ROOM_SIZE --json        # look up any error code
arch repair plan.arch -o fixed.arch    # explicit corrector: new source w/ furniture out of walls/doorways/swings, overlaps separated, fixtures into their room + snapped to walls + change log
arch batch a.arch b.arch -f svg --json # render many variants at once → results[]
arch md notes.md -o out.md -f svg      # render every fenced arch block in a Markdown file → image links
\`\`\`

**Self-correction loop:** compile/validate → if \`ok\` is false, read each \`diagnostics[].fix\` (and
\`line\`/\`col\`/\`span\`), edit the source, recompile. Exit code \`2\` means a deterministic
user-source error (fix it; don't blindly retry). Then \`describe --json\` to confirm the plan matches
intent (right room count, areas, adjacency) without rendering an image. **Before shipping, gate with
\`arch validate --strict --json\`** — it fails on advisory warnings too, so a plan that lint flags
(furniture through a wall, a fixture blocking a doorway, a room you can't step into, an unreachable
room) cannot pass silently.

**Place furniture so it's physically sound:** keep every piece inside its room and off the walls
(don't cross a wall centerline); back plumbing/kitchen fixtures onto a wall with \`against wall <id>\`
(+ \`in <roomId>\`) rather than guessing an \`at\`; give every room a \`door\`/\`opening\`; and leave
the doorway approach and the door's swing clear.

**Fix topology from facts, not guesses.** \`arch repair\` corrects furniture but never adds a door or
window (that is a design choice). When lint reports an unreachable room / no entrance / windowless
bedroom, read \`describe --json\` — \`access.rooms[].reachable\`, room \`bbox\`/\`adjacent\`, building
extent = min/max of room boxes — and add a \`door\`/\`opening\`/\`window\` on the right wall yourself
(an exterior entrance into a cut-off living space beats routing through a bedroom), then re-\`repair\`
and \`validate --strict\`. See SKILL.md for the exact arithmetic.

## Common mistakes

| Mistake | Fix |
| --- | --- |
| Using metres (\`size 4x3\`) | Use millimetres (\`size 4000x3000\`). |
| Expecting +y to go up | +y goes **down**; a room below another has a larger y. |
| Door/window floating in space | Put its \`at\` on a wall segment's centerline. |
| \`size 4000\` (no height) | Sizes are \`WxH\`: \`size 4000x3000\` (or \`W x H\` with spaces). |
| Reusing an \`id\` | Ids are unique; omit \`id=\` to auto-generate. |
| String math without interpolation | Use \`"{expr}"\`, e.g. \`label "{aream2(W,H)} m²"\`. |

## Worked examples

${exampleBlocks}
`;
}

/** Read the embedded example files from disk (CLI/main path only). */
function readExamples(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const name of SPEC_EXAMPLES) {
    out[name] = readFileSync(resolve(ROOT, "examples", name), "utf8");
  }
  return out;
}

function main(): void {
  writeFileSync(resolve(ROOT, "spec.llm.md"), renderLlmSpec(readExamples()));
  process.stdout.write("✓ generated spec.llm.md from src/grammar/tokens.ts + examples/\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
