/**
 * Generate `docs/cli-reference.md` — the complete `arch` CLI reference — from the
 * capability manifest (`src/manifest.ts`), the same source `arch manifest --json`
 * serves.
 *
 * Why generated: the CLI grew from 13 verbs to 20 across v1.8 → v1.15 while the
 * hand-written site pages stayed frozen, so the docs told agents about a CLI that no
 * longer existed. Deriving the page from the manifest makes that impossible — add a
 * command without regenerating and `npm run check:drift` fails.
 *
 * {@link renderCliReference} is pure (no fs, no clock) so the drift test can call it
 * in-memory. Run `npm run gen:cli` after touching the command table.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { buildManifest, type ManifestExample, type ManifestFlag } from "../src/manifest.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

/**
 * Escape `<`/`>` for markdown *prose* (outside a code span). VitePress compiles pages as
 * Vue templates, so a bare `<file.arch|->` — or the `--accessible` flag's literal
 * `<title>`/`<desc>` — is parsed as an unclosed HTML tag and fails the build with
 * "Element is missing end tag". Inside backticks the brackets are already safe; this is
 * for the places that aren't.
 */
const prose = (s: string): string => s.replace(/</g, "&lt;").replace(/>/g, "&gt;");

/**
 * Escape a `|` in a GFM table cell. GFM splits cells on `|` *before* inline code is parsed,
 * so a bare pipe severs the backtick pair and leaks the `<placeholder>` inside it as raw
 * HTML. (That took the docs deploy down for four pushes on 2026-07-12; see AGENTS.md.)
 * Angle brackets are NOT touched here — inside a code span markdown escapes them for us,
 * and escaping them again would render a literal `&lt;`.
 */
const codeCell = (s: string): string => s.replace(/\|/g, "\\|");

/** A prose table cell: needs the pipe escape *and* the angle-bracket escape. */
const proseCell = (s: string): string => codeCell(prose(s));

/** `--flag, -a <arg>` as one inline-code span. */
function flagSignature(f: ManifestFlag): string {
  const name = f.alias ? `${f.flag}, ${f.alias}` : f.flag;
  return `\`${name}${f.arg ? ` ${f.arg}` : ""}\``;
}

function flagTable(flags: readonly ManifestFlag[]): string {
  if (flags.length === 0) return "_No command-specific flags._\n";
  return [
    "| Flag | Does |",
    "| --- | --- |",
    ...flags.map((f) => `| ${codeCell(flagSignature(f))} | ${proseCell(f.description)} |`),
    "",
  ].join("\n");
}

/**
 * The command's worked invocations, as a bash fence. A fence — not a table — on
 * purpose: an example line carries `|`, `<`, `>` and `*` freely, and inside a fenced
 * block markdown neither splits cells nor hands the brackets to the Vue compiler, so
 * none of the {@link prose}/{@link codeCell} escaping applies (and must not: an escaped
 * `\|` would be copy-pasted verbatim into a shell).
 */
function exampleFence(examples: readonly ManifestExample[]): string {
  const body = examples.map((e) => `# ${e.note}\n$ ${e.cmd}`).join("\n\n");
  return ["**Examples**", "", "```bash", body, "```", ""].join("\n");
}

/** Render the whole CLI reference page (string). Pure — safe for the drift test. */
export function renderCliReference(): string {
  // Only the command/flag/format/exit-code tables are read; the page never prints a
  // version, so a constant keeps this pure (no package.json read).
  const m = buildManifest("0.0.0");

  const out: string[] = [
    "<!-- GENERATED by scripts/gen-cli-reference.ts from src/manifest.ts — do not edit by hand. Run `npm run gen:cli`. -->",
    "",
    "# CLI reference",
    "",
    "Every `arch` command, flag, format and exit code — generated from the same capability",
    "manifest that `arch manifest --json` serves, so this page cannot fall behind the CLI.",
    "",
    "The CLI is ArchLang's **primary agent interface**. Every command takes `--json` (structured",
    "result on **stdout**, human messages on **stderr**), and every command that reads source",
    "accepts a file path or `-` for stdin.",
    "",
    "```bash",
    "npx @chanmeng666/archlang help     # zero-install",
    "arch manifest --json               # this page, as data",
    "```",
    "",
    "## Exit codes",
    "",
    "| Code | Meaning |",
    "| --- | --- |",
    ...Object.entries(m.exitCodes).map(([code, meaning]) => `| \`${code}\` | ${proseCell(meaning)} |`),
    "",
    "## Output formats",
    "",
    "`-f <format>` on `compile`, `batch`, `md` and `preview`.",
    "",
    "| Format | Dependency |",
    "| --- | --- |",
    ...m.formats.map(
      (f) => `| \`${f.id}\` | ${f.zeroDep ? "zero-dep (built in)" : `needs optional \`${f.optionalDep}\``} |`,
    ),
    "",
    "## Global flags",
    "",
    flagTable(m.globalFlags),
    "## Commands",
    "",
  ];

  for (const c of m.commands) {
    const aliases = c.aliases?.length ? ` _(alias: ${c.aliases.map((a) => `\`${a}\``).join(", ")})_` : "";
    out.push(
      `### \`arch ${c.name}\`${aliases}`,
      "",
      prose(c.summary),
      "",
      `**Input:** \`${c.input}\` · **Output:** ${prose(c.output)}`,
      "",
      flagTable(c.flags),
      exampleFence(c.examples),
    );
  }

  return out.join("\n").replace(/\n+$/, "\n");
}

function main(): void {
  writeFileSync(resolve(ROOT, "docs/cli-reference.md"), renderCliReference());
  process.stdout.write("✓ generated docs/cli-reference.md from src/manifest.ts\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
