/**
 * The ArchLang diagnostic catalog: every `E_*` / `W_*` code with its cause, fix,
 * and a tiny example. One source for `arch explain <CODE>` and the generated
 * `docs/error-codes.md` (see `scripts/gen-error-codes.ts`). The codes themselves
 * are raised across `src/` (validate/resolve/import/builtins/elements); this file
 * documents them.
 */

export interface CatalogEntry {
  code: string;
  severity: "error" | "warning";
  /** One-line summary. */
  message: string;
  /** Why the compiler raises it. */
  cause: string;
  /** How to resolve it. */
  fix: string;
  /** A minimal snippet illustrating the cause (or the fix). */
  example: string;
}

const E = (code: string, message: string, cause: string, fix: string, example: string): CatalogEntry => ({
  code,
  severity: "error",
  message,
  cause,
  fix,
  example,
});
const W = (code: string, message: string, cause: string, fix: string, example: string): CatalogEntry => ({
  code,
  severity: "warning",
  message,
  cause,
  fix,
  example,
});

/** The catalog, keyed by code. Frozen so it cannot be mutated at runtime. */
export const ERROR_CATALOG: Readonly<Record<string, CatalogEntry>> = Object.freeze({
  E_ACC_PLACEMENT: E(
    "E_ACC_PLACEMENT",
    "`accTitle`/`accDescr` used outside the plan level.",
    "An `accTitle` or `accDescr` accessibility-metadata statement appeared inside a component or a control-flow block. They describe the whole plan, so they are only legal as direct plan-level statements.",
    "Move the `accTitle`/`accDescr` line up to the plan body, alongside `units`/`north`.",
    'component c() { accDescr "x" }   # error: only allowed at plan level',
  ),
  E_ARGCOUNT: E(
    "E_ARGCOUNT",
    "Component called with the wrong number of arguments.",
    "A component instance supplies more or fewer arguments than the component declares parameters.",
    "Pass exactly one argument per declared parameter.",
    "component bed(x, y) { … }\nbed(300)        # error: expects 2 arguments",
  ),
  E_ARITY: E(
    "E_ARITY",
    "Built-in function called with the wrong number of arguments.",
    "A built-in (e.g. abs, sqrt, len) was called with the wrong argument count.",
    "Check the function's arity; most built-ins take one argument.",
    "let x = abs(1, 2)   # error: abs expects 1 argument",
  ),
  E_ASSIGN_UNDEF: E(
    "E_ASSIGN_UNDEF",
    "Assignment to an undeclared name.",
    "`NAME = value` was used for a name never introduced with `let`.",
    "Declare it first with `let`, or fix a typo in the name.",
    "x = 5           # error: declare with `let x = …` first",
  ),
  E_CALL_DEPTH: E(
    "E_CALL_DEPTH",
    "Value-function call stack too deep.",
    "A value-function recurses (directly or mutually) beyond the call-depth limit.",
    "Make the recursion terminate, or rewrite it iteratively with a bounded `while`.",
    "let f(n) = f(n + 1)   # error: never terminates",
  ),
  E_COLUMN_SIZE: E(
    "E_COLUMN_SIZE",
    "Column must have a positive size.",
    "A column's width or height evaluated to zero or a negative number.",
    "Give the column a positive `size W x H`.",
    "column at (0,0) size 0x300   # error: width is 0",
  ),
  E_DIV_ZERO: E(
    "E_DIV_ZERO",
    "Division or modulo by zero.",
    "An expression divides (or takes a remainder) by a value that evaluates to zero.",
    "Guard the divisor, or use a non-zero value.",
    "let x = 10 / 0   # error",
  ),
  E_DOMAIN: E(
    "E_DOMAIN",
    "Math domain error.",
    "A built-in received an out-of-domain argument (e.g. `sqrt` of a negative number).",
    "Pass a value within the function's domain.",
    "let x = sqrt(-1)   # error",
  ),
  E_DOOR_WIDTH: E(
    "E_DOOR_WIDTH",
    "Door must have a positive width.",
    "A door's width evaluated to zero or a negative number.",
    "Give the door a positive `width`.",
    "door at (0,0) width 0   # error",
  ),
  E_DUP_ID: E(
    "E_DUP_ID",
    "Duplicate element id.",
    "Two elements declare the same `id=…`; ids must be unique across the plan.",
    "Rename one of them, or drop the explicit id to auto-generate a unique one.",
    'room id=a at (0,0) size 1x1\nroom id=a at (1,0) size 1x1   # error: duplicate id "a"',
  ),
  E_DUP_INSTANCE: E(
    "E_DUP_INSTANCE",
    "Duplicate `place … as <name>` instance name.",
    "Two `place` statements claim the same instance name. The name is the id NAMESPACE for everything inside the instance, so reusing it would silently merge two instances' ids.",
    "Give each instance its own name (`as west` / `as east`).",
    'place wing() as west at (0,0)\nplace wing() as west at (9000,0)   # error: instance "west" already used',
  ),
  E_DOTTED_DECL: E(
    "E_DOTTED_DECL",
    "A dotted name cannot be declared.",
    "A dotted name like `west.main` addresses an element INSIDE a `place`d instance. The namespace belongs to the `place`, so a dotted name is only ever a reference — it can never be declared with `id=`, `let`, `as`, or `for`.",
    "Declare the short name and address it from outside as `<instance>.<name>`.",
    "room id=main at (0,0) size 3000x3000   # then, in the plan: furniture bed in west.main centered",
  ),
  E_FURN_SIZE: E(
    "E_FURN_SIZE",
    "Furniture must have a positive size.",
    "A furniture item's width or height evaluated to zero or a negative number.",
    "Give the item a positive `size W x H`.",
    "furniture bed at (0,0) size 0x2000   # error",
  ),
  E_FURN_ROOM: E(
    "E_FURN_ROOM",
    "Furniture placed `in` an unknown room.",
    "A furniture item names a room with `in <roomId>`, but no room has that id.",
    "Use the id of an existing `room id=…`, or drop the `in` clause.",
    "furniture bed at (0,0) size 1500x2000 in bedrm   # error: no room id=bedrm",
  ),
  E_FURN_ROTATE: E(
    "E_FURN_ROTATE",
    "Furniture rotation must be a quarter-turn.",
    "A furniture item's `rotate` is not one of 0, 90, 180, or 270 degrees.",
    "Use a quarter-turn: `rotate 0|90|180|270`.",
    "furniture wc at (0,0) size 400x700 rotate 45   # error: not a quarter-turn",
  ),
  E_FURN_AGAINST: E(
    "E_FURN_AGAINST",
    "Invalid `against wall` fixture placement.",
    "A wall-anchored fixture references an unknown wall, omits `segment` on a multi-segment wall, omits `side`, sits on a non-axis-aligned segment, has an out-of-range offset, or also sets `rotate`. The compiler will not guess which wall/side/segment was meant.",
    "Name an existing wall id, add `segment <n>` for multi-segment walls, give `side left|right`, keep the segment axis-aligned, and drop any explicit `rotate`.",
    "furniture wc against wall w1 side left size 400x700   # error if w1 is unknown or multi-segment",
  ),
  E_FURN_FLUSH: E(
    "E_FURN_FLUSH",
    "`flush` on a placement that touches no edge.",
    "`flush` measures `inset` from the inner face of the wall behind an *anchored edge*. A `centered` piece (or the equivalent `anchor center`) is pushed against no edge, so there is no wall face to measure from.",
    "Anchor the piece to the edge you want it flush with (`anchor bottom flush`, `anchor top-left flush`), or drop `flush` and keep it centred.",
    "furniture wc in bath centered flush size 400x700   # error: centred, so nothing to be flush with",
  ),
  E_ATTACH_WALL_REF: E(
    "E_ATTACH_WALL_REF",
    "Opening attached to an unknown or ambiguous wall.",
    "A `door`/`window`/`opening … on <wall> at <pos>` names a wall id (or category) that no wall has, or one that matches more than one wall — so the compiler cannot pick the polyline to walk.",
    "Reference an existing, unique wall id (add `id=` to the wall if needed).",
    "door on w1 at 40% width 900   # error if no wall id=w1 (or several match)",
  ),
  E_ATTACH_POS_RANGE: E(
    "E_ATTACH_POS_RANGE",
    "Opening attachment position is out of range.",
    "The `at <pos>` of an attached opening is outside the host wall: a percentage outside 0–100%, or a millimetre distance outside `0 … wall length`.",
    "Use a percentage in 0–100%, a millimetre distance within the wall's run, or `center`.",
    "door on w1 at 150% width 900   # error: 150% is past the wall end",
  ),
  E_PLACE_REF: E(
    "E_PLACE_REF",
    "Furniture placed in an unknown or non-absolute room.",
    "A `furniture … in <room> centered|anchor …` names a room that does not exist, or one positioned relationally (`right-of`/…) whose box is not yet fixed when the fixture is placed.",
    "Reference an existing room given absolute `at (x,y)` coordinates.",
    "furniture bed in bedrm centered size 1500x2000   # error: no room id=bedrm",
  ),
  E_PLACE_POLY: E(
    "E_PLACE_POLY",
    "A rectangle-only placement clause aimed at a polygon room.",
    "Relational room placement (`right-of`/`left-of`/`below`/`above`) and room-relative furniture placement (`in <room> centered|anchor …`) are closed-form arithmetic on a room's four RECTANGLE edges. A `room polygon` has no such edges, and its bounding box is not its floor — an anchor could land the piece in a notch that is outside the room — so the compiler refuses instead of guessing (ADR 0005).",
    "Place the room or the fixture with explicit `at (x,y)` coordinates (a fixture may add `rotate`), or make the referenced room rectangular.",
    "room id=L polygon (0,0) (6000,0) (6000,4000) (3000,4000) (3000,6000) (0,6000)\nfurniture wc in L anchor bottom-left   # error: L is a polygon room",
  ),
  E_DIM_CURVE_REF: E(
    "E_DIM_CURVE_REF",
    "Invalid `dim radius`/`dim diameter` reference.",
    "A curve call-out references an element that does not exist, is not the right shape (a `diameter` on a rectangular room, a `radius` on a wall with no `arc` edge), matches several walls, or omits `segment <n>` on a wall with more than one arc. The compiler will not guess which curve was meant.",
    "Name an existing, unique wall id whose edge is an `arc` (adding `segment <n>` when it has several), or an existing `room circle` id for `diameter`.",
    "dim radius w1   # error if w1 is straight, unknown, or has two arc edges",
  ),
  E_ARC_RADIUS: E(
    "E_ARC_RADIUS",
    "Arc radius too small for its chord.",
    "An `arc (x,y) radius R` edge asks for a circle of radius R through the previous vertex and this one, but R is less than half the straight-line distance between them (or is not positive) — no such circle exists.",
    "Raise the radius to at least half the chord (the message states the minimum), or move the endpoints closer together. `arch fix` applies the minimum for you.",
    "wall exterior thickness 200 { (0,0) arc (10000,0) radius 3000 }   # error: needs R >= 5000",
  ),
  E_ROOM_RADIUS: E(
    "E_ROOM_RADIUS",
    "Circular room needs a positive radius.",
    "A `room circle at (cx,cy) radius R` has R of zero or less, so it encloses no floor — there is no area, no centroid and no containment test to compute.",
    "Give the room a positive radius in millimetres.",
    "room circle at (5000,5000) radius 0   # error: no floor",
  ),
  E_ROOM_POLY_DEGENERATE: E(
    "E_ROOM_POLY_DEGENERATE",
    "Polygon room has fewer than three effective vertices.",
    "After removing duplicate and straight-through (collinear) points, the ring encloses no area — so it has no floor, no centroid and no containment test.",
    "Give the room at least three vertices that actually turn a corner.",
    "room polygon (0,0) (4000,0) (8000,0)   # error: all three are collinear",
  ),
  E_ROOM_POLY_SELF_INTERSECT: E(
    "E_ROOM_POLY_SELF_INTERSECT",
    "Polygon room intersects itself.",
    "Two of the ring's edges cross (or run along each other), so the polygon is not simple and which side is 'inside' is undefined — area, containment and adjacency would all be meaningless.",
    "Reorder the vertices so the ring is traced once around the room without crossing itself (a bow-tie usually means two vertices are swapped).",
    "room polygon (0,0) (4000,4000) (4000,0) (0,4000)   # error: bow-tie",
  ),
  E_SITE_DUP: E(
    "E_SITE_DUP",
    "Two `site` blocks in one plan.",
    "A plan declares `site` more than once. `axes` merges when repeated because two axis lists *append*; two `street` values **contradict**, and silently keeping the last one would hide an authoring mistake in the very statement whose job is to be the single source of orientation.",
    "Delete one of the blocks, or merge their fields into a single `site { … }`. The first block is the one that takes effect.",
    'plan "H" {\n  units mm\n  site { street south }\n  site { street north }   # error: site already declared\n}',
  ),
  E_SITE_NO_STREET: E(
    "E_SITE_NO_STREET",
    "A `site` block declares no `street`.",
    "`street` is the only required field of `site`: every derived name (`back`, and the three `_side` names) is a function of it, so a site without one derives nothing at all. Refusing beats defaulting — there is no direction a building's frontage faces by default.",
    "Add `street north`, `south`, `east` or `west` inside the block. `hemisphere` is the optional field (it defaults to `north`).",
    'plan "H" {\n  units mm\n  site { hemisphere south }   # error: no street\n}',
  ),
  E_STRIP_SIZE: E(
    "E_STRIP_SIZE",
    "Room in a `strip` is missing a size.",
    "A room inside a `strip { … }` gives no main-axis extent, or gives none while the strip supplies no cross-axis `height`/`width` for it to inherit — so its rectangle is undetermined.",
    "Give the room a `size <main>` (main-axis extent) plus either a strip `height`/`width` or its own `size <main>x<cross>`.",
    "strip right at (0,0) gap 100 { room size }   # error: no extent",
  ),
  E_STRIP_NEST: E(
    "E_STRIP_NEST",
    "Illegal `strip` nesting.",
    "A `strip` block appears inside a component, a control-flow block, or another `strip`. Strips place rooms and are only legal as direct plan-level statements.",
    "Move the `strip` to the plan body, alongside the other elements.",
    "component c() { strip right at (0,0) gap 0 { … } }   # error: nested strip",
  ),
  E_VERT_SIZE: E(
    "E_VERT_SIZE",
    "Vertical circulation must have a positive size.",
    "A `stair`, `elevator` or `escalator` footprint's width or height evaluated to zero or a negative number, so there is no run to draw.",
    "Give it a positive `size W x H` — the footprint the run occupies on this storey.",
    "stair id=s at (0,0) size 900x0 dir up   # error: zero depth",
  ),
  E_STAIR_WIDTH: E(
    "E_STAIR_WIDTH",
    "Stair flight `width` is outside the footprint.",
    "A `stair`'s optional `width` is the FLIGHT width measured across the run, so it has to be positive and no wider than the footprint's cross-axis extent (the short side — the flight always runs along the long one). This value is not.",
    "Drop `width` to fill the footprint, or give a value between 0 and the footprint's short side.",
    "stair id=s at (0,0) size 900x2600 dir up width 1200   # error: cross extent is 900",
  ),
  E_IMPORT_BAD_SPEC: E(
    "E_IMPORT_BAD_SPEC",
    "Malformed import spec.",
    "The string after `import` is not a recognizable module reference.",
    'Use a relative path ("lib/x.arch") or a namespaced spec ("@scope/name:1.0.0").',
    'import "???" : a   # error',
  ),
  E_IMPORT_CONFLICT: E(
    "E_IMPORT_CONFLICT",
    "Imported name conflicts with an existing component.",
    "An imported component has the same name as one already defined or imported.",
    "Rename with `as`, or remove the duplicate.",
    'import "lib.arch": bed as lib_bed',
  ),
  E_IMPORT_CYCLE: E(
    "E_IMPORT_CYCLE",
    "Cyclic import.",
    "Modules import each other in a cycle, which cannot be resolved.",
    "Break the cycle so module dependencies form a tree.",
    "# a.arch imports b.arch which imports a.arch  → error",
  ),
  E_IMPORT_NOT_EXPORTED: E(
    "E_IMPORT_NOT_EXPORTED",
    "Imported name is not exported by the module.",
    "The module has no component with the requested name.",
    "Import a name the module actually defines (check its `component`s).",
    'import "lib.arch": nope   # error if lib.arch has no `component nope`',
  ),
  E_IMPORT_NOT_FOUND: E(
    "E_IMPORT_NOT_FOUND",
    "Import path could not be resolved.",
    "The World could not read the module at the given path.",
    "Check the path (relative to the importing file) and that the file exists.",
    'import "lib/missing.arch": a   # error',
  ),
  E_IMPORT_PARSE: E(
    "E_IMPORT_PARSE",
    "Imported module has a parse error.",
    "The module referenced by `import` does not itself parse.",
    "Fix the syntax error in the imported module.",
    "# error originates in the imported file",
  ),
  E_INDEX: E(
    "E_INDEX",
    "Array index out of range.",
    "`arr[i]` used an index outside `0 .. len(arr) - 1`.",
    "Clamp or check the index against `len(arr)`.",
    "let a = [1, 2]\nlet x = a[5]   # error",
  ),
  E_INTENT_NOT_ADJACENT: E(
    "E_INTENT_NOT_ADJACENT",
    "Two rooms the brief wants adjacent share no interior door.",
    "An intent `adjacency` edge names two concepts (e.g. hall ↔ bathroom) that are not joined by an interior door or cased opening in the plan's modeled connectivity.",
    "Add a `door` (or `opening`) on the wall the two rooms share so they are directly connected. Advisory tier: this is scored and reported by `validateIntent` but does NOT fail `ok` (gate: false) — one-shot topology is what the loop tools address.",
    "door on wall_hall_bath width 800   # connect the hall to the bathroom",
  ),
  E_INTENT_NO_DOOR: E(
    "E_INTENT_NO_DOOR",
    "The plan has no modeled entrance, so `reachable` cannot hold.",
    "An intent asserts `reachable: true`, but the plan has no door connecting a room to the exterior — nothing is enterable, so no room is reachable.",
    "Add an exterior entrance `door` on a perimeter wall. Advisory tier: reported and scored by `validateIntent` but does NOT fail `ok` (gate: false).",
    "door on exterior at 50% width 900   # a front door",
  ),
  E_INTENT_NO_SITE: E(
    "E_INTENT_NO_SITE",
    "An intent asserts a SYMBOLIC window facing against a plan with no `site`.",
    "An intent `roomsInclude[].windows.facing` names one of the derived directions (`street`, `back`, `equator_side`, `sunrise_side`, `sunset_side`) but the plan declares no `site` block, so there is nothing to resolve the name against. The question is unanswerable, not answered no.",
    "Declare `site { street … }` in the plan (that is what gives the derived names their letters), or assert a plain compass letter instead. Gating tier: this failure fails `validateIntent`'s `ok` — it is a refusal, never a silent pass and never a silent miss.",
    'plan "H" {\n  units mm\n  site { street south }   # now `facing: "equator_side"` resolves to "S"\n}',
  ),
  E_INTENT_NO_WINDOW: E(
    "E_INTENT_NO_WINDOW",
    "A room the brief wants a window in has too few.",
    'An intent `roomsInclude[].windows` requires at least one window in a concept\'s room(s) (e.g. "give the bedroom a window"), but the plan places fewer than the required count.',
    "Add a `window` on one of that room's walls. Gating tier: this failure DOES fail `validateIntent`'s `ok`.",
    "window on north at 40% width 1200   # light the bedroom",
  ),
  E_INTENT_ROOM_AREA: E(
    "E_INTENT_ROOM_AREA",
    "A named room's floor area is outside the brief's band.",
    'An intent `roomsInclude[].areaM2` gives a per-room area band (from a number in the brief, ±10% for "about N"), but the matched room\'s area falls outside it.',
    "Resize the room so its floor area lands in the band. Gating tier: this failure fails `validateIntent`'s `ok`. Assert a band only where the brief states a number — qualitative size words license none.",
    'room at (0,0) size 4000x3000 label "Bedroom"   # 12 m²',
  ),
  E_INTENT_ROOM_COUNT: E(
    "E_INTENT_ROOM_COUNT",
    "The plan's room count does not match the brief.",
    "An intent `rooms` count (asserted only when the brief ENUMERATES its rooms) does not match the plan's room total. A single surplus room passes only when it is pure circulation (a hall/corridor) — policy B.",
    "Add or remove rooms to reach the enumerated count. Gating tier: this failure fails `validateIntent`'s `ok`.",
    "# brief lists 4 rooms; the plan draws 5 (and the extra is a bedroom, not a hall)",
  ),
  E_INTENT_ROOM_MISSING: E(
    "E_INTENT_ROOM_MISSING",
    "A room the brief names is absent from the plan.",
    'An intent `roomsInclude[]` concept (e.g. "bathroom") matched no room by label, `room_type`, or `uses` — the plan is missing a room the brief asked for.',
    "Add a `room` whose label, `uses`, or type matches the concept. Gating tier: this failure fails `validateIntent`'s `ok`.",
    'room at (0,0) size 2000x2000 label "Bathroom" uses bath   # supply the missing room',
  ),
  E_INTENT_TOTAL_AREA: E(
    "E_INTENT_TOTAL_AREA",
    "The plan's total floor area is outside the brief's band.",
    'An intent `totalAreaM2` band (from a number in the brief, ±10% for "about N") does not contain the plan\'s total floor area.',
    "Grow or shrink rooms so the total lands in the band. Gating tier: this failure fails `validateIntent`'s `ok`. Assert a band only where the brief states a number.",
    '# brief says "about 42 m²" (band 37.8–46.2); the plan totals 52 m²',
  ),
  E_INTENT_UNREACHABLE: E(
    "E_INTENT_UNREACHABLE",
    "A room cannot be reached from the entrance through modeled doors.",
    "An intent asserts `reachable: true` and the plan HAS an entrance, but one or more rooms are cut off — no chain of modeled doors reaches them from the exterior.",
    "Add interior doors so every room connects back to the entrance. Advisory tier: reported and scored by `validateIntent` but does NOT fail `ok` (gate: false).",
    "door on wall_hall_store width 800   # connect the isolated room",
  ),
  E_JSON_SCHEMA: E(
    "E_JSON_SCHEMA",
    "Plan JSON does not match the schema.",
    "A value passed to `planFromJson` has the wrong shape or type for its JSON path (e.g. a room missing a numeric `width`, a non-array `rooms`), or it uses a construct the JSON form cannot represent — scripting (`let`/`for`/`if`/`component`) and `import` are intentionally not supported.",
    "Fix the value at the reported JSON path (the message names it, e.g. `/rooms/0/width`); express geometry as concrete numbers, and author scripting/imports in `.arch` source instead.",
    '{ "rooms": [ { "x": 0, "y": 0, "width": "big", "height": 3000 } ] }   # error at /rooms/0/width: expected a number',
  ),
  E_JSON_KIND: E(
    "E_JSON_KIND",
    "Unknown element kind in plan JSON.",
    "An element in the JSON names a `kind` (or lives in an array) the builder does not recognize — e.g. an opening whose `kind` is not `door`, `window`, or `opening`.",
    "Use one of the supported kinds: opening `kind` must be `door` | `window` | `opening`.",
    '{ "openings": [ { "kind": "portal", "width": 900 } ] }   # error at /openings/0/kind: unknown kind "portal"',
  ),
  E_LAYOUT_CYCLE: E(
    "E_LAYOUT_CYCLE",
    "Relational room placement forms a cycle.",
    "Rooms placed with `right-of`/`below`/… reference each other in a loop, so no order resolves them.",
    "Break the cycle by giving one of the rooms absolute `at (x,y)` coordinates.",
    "room id=a right-of b size 100x100\nroom id=b left-of a size 100x100   # error: a ↔ b cycle",
  ),
  E_LAYOUT_REF: E(
    "E_LAYOUT_REF",
    "Relational placement references an unknown room.",
    "A `right-of`/`below`/… clause names a room id that does not exist in the plan.",
    "Reference an existing room id, or fix the typo.",
    'room id=k right-of ghost size 100x100   # error: no room "ghost"',
  ),
  E_LEVEL_DUP: E(
    "E_LEVEL_DUP",
    "Two `level` blocks declare the same storey number.",
    "Level numbers identify the storeys of one building, so each may be declared once; two `level 1` blocks would produce two pages both claiming to be level 1.",
    "Renumber one of them, or merge the two bodies into a single `level` block.",
    "level 1 { room at (0,0) size 3000x3000 }\nlevel 1 { room at (0,0) size 3000x3000 }   # error: level 1 twice",
  ),
  E_LEVEL_MIX: E(
    "E_LEVEL_MIX",
    "A drawable statement sits beside `level` blocks.",
    "A plan is either single-storey (no `level` block) or entirely made of them: anything that draws belongs to exactly one storey, so a room/wall/door/`for`/`strip`/component call at plan level next to a `level` block has no storey to belong to.",
    "Move the statement inside the `level` block it belongs to. Only settings (`units`/`grid`/`paper`/`scale`/`north`/`site`/`dims`/`title`/`axes`/`schedule`/`legend`), `component`/`import` declarations, and the plan-global `let`/`set` stay outside — they apply to every level.",
    'plan "H" {\n  room at (0,0) size 3000x3000   # error: move it into a level\n  level 1 { wall exterior thickness 200 { (0,0) (3000,0) close } }\n}',
  ),
  E_LEVEL_NEST: E(
    "E_LEVEL_NEST",
    "`level` used inside a block or component.",
    "A `level` block is a plan-level statement: it partitions the whole plan into storeys, so it cannot be nested inside another `level`, a `for`/`if`/`while` body, a `strip`, or a component definition.",
    "Move the `level` block out to the plan body. To draw the same content on several storeys, put it in a `component` and call it from each level.",
    "component c() { level 1 { } }   # error: only allowed at plan level",
  ),
  E_RANGE_LIMIT: E(
    "E_RANGE_LIMIT",
    "Range too large.",
    "A `lo..hi` range would expand to more elements than the safety cap allows.",
    "Use a smaller range, or restructure to avoid materializing it.",
    "for i in 0..1000000 { … }   # error: range too large",
  ),
  E_RECURSION: E(
    "E_RECURSION",
    "Component recursion too deep.",
    "Component instantiation nested beyond the depth limit (usually unbounded self-instantiation).",
    "Add a base case so the recursion terminates.",
    "component r(n) { r(n) }   # error: never terminates",
  ),
  E_REDEF: E(
    "E_REDEF",
    "Name already defined in this scope.",
    "A `let` re-declares a name already bound in the same scope.",
    "Rename one binding, or use `NAME = …` to reassign instead of redeclaring.",
    "let x = 1\nlet x = 2   # error: redefinition",
  ),
  E_ROOM_SIZE: E(
    "E_ROOM_SIZE",
    "Room must have a positive size.",
    "A room's width or height evaluated to zero or a negative number.",
    "Give the room a positive `size W x H`.",
    "room at (0,0) size 0x4000   # error: width is 0",
  ),
  E_TYPE: E(
    "E_TYPE",
    "Type mismatch.",
    "A value was used where another type was required (e.g. a string where a number is expected, or a non-array in `for`).",
    "Convert or supply the expected type.",
    'room at (0,0) size "big" x 10   # error: size needs numbers',
  ),
  E_UNKNOWN_COMPONENT: E(
    "E_UNKNOWN_COMPONENT",
    "Unknown component.",
    "An instance calls a component name that is not defined or imported.",
    "Define the component, import it, or fix the name (see the suggestion hint).",
    "sofa(0, 0)   # error if no `component sofa` is in scope",
  ),
  E_UNKNOWN_FN: E(
    "E_UNKNOWN_FN",
    "Unknown function.",
    "A call uses a name that is neither a built-in nor a value-function in scope.",
    "Define it with `let f(…) = …`, or fix the name.",
    "let x = frobnicate(2)   # error",
  ),
  E_UNKNOWN_REF: E(
    "E_UNKNOWN_REF",
    "Unknown reference.",
    "An expression references a name that is not bound in scope.",
    "Declare it with `let`, pass it as a parameter, or fix the typo.",
    "let x = y + 1   # error if `y` is undefined",
  ),
  E_WALL_THICKNESS: E(
    "E_WALL_THICKNESS",
    "Wall must have a positive thickness.",
    "A wall's `thickness` evaluated to zero or a negative number.",
    "Give the wall a positive `thickness`.",
    "wall exterior thickness 0 { (0,0) (1,0) }   # error",
  ),
  E_WHILE_LIMIT: E(
    "E_WHILE_LIMIT",
    "`while` exceeded its iteration cap.",
    "A `while` ran more times than the safety cap allows (usually a condition that never becomes false).",
    "Ensure the loop body updates a binding so the condition eventually fails.",
    "let i = 0\nwhile i < 1 { column at (0,0) size 1x1 }   # error: i never changes",
  ),
  E_WINDOW_WIDTH: E(
    "E_WINDOW_WIDTH",
    "Window must have a positive width.",
    "A window's width evaluated to zero or a negative number.",
    "Give the window a positive `width`.",
    "window at (0,0) width 0   # error",
  ),
  E_OPENING_WIDTH: E(
    "E_OPENING_WIDTH",
    "Opening must have a positive width.",
    "A cased opening's width evaluated to zero or a negative number.",
    "Give the opening a positive `width`.",
    "opening at (0,0) width 0   # error",
  ),
  E_PNG_DEPENDENCY: E(
    "E_PNG_DEPENDENCY",
    "PNG/PDF export needs an optional dependency that is not installed.",
    "Rendering to PNG needs `@resvg/resvg-js` (PDF needs `pdfkit`); the optional binary is absent in this environment (it is not bundled, to keep the core zero-dependency).",
    "Install the optional dependency (`npm install @resvg/resvg-js`), or re-run with `--install` to fetch it automatically, or render to SVG/DXF (zero-dependency).",
    "arch preview plan.arch --install   # fetches @resvg/resvg-js, then renders the PNG",
  ),

  W_IMPORT_EMPTY_FILE: W(
    "W_IMPORT_EMPTY_FILE",
    "Whole-file import binds an empty component.",
    "`import \"<file>\" as <name>` turns a module's TOP-LEVEL drawable statements into one component, but that module's plan body has none (it may only declare `component`s, or only `level` blocks — a storey is a page, so levels are dropped).",
    'Draw in the module\'s plan body, or import one of its named components with `import "<file>": <name>`.',
    'import "lib.arch" as lib   # warning when lib.arch only declares components',
  ),
  W_DUP_ACC_METADATA: W(
    "W_DUP_ACC_METADATA",
    "Duplicate `accTitle`/`accDescr`.",
    "A plan declares `accTitle` (or `accDescr`) more than once. Only one of each applies, so the last value silently wins.",
    "Keep a single `accTitle` and a single `accDescr`; delete the extra line(s).",
    'accTitle "A"\naccTitle "B"   # warning: "A" is discarded',
  ),
  W_SWING_ROOM_NOT_ADJACENT: W(
    "W_SWING_ROOM_NOT_ADJACENT",
    "`swing into <room>` names a room the door does not border.",
    "A door's `swing into <room>` points the leaf toward a room, but that room does not share the door's host wall (its box does not touch the wall within tolerance), so which side it means is undefined.",
    "Point `swing into` at a room the door actually opens onto, or use explicit `swing in|out`. The door falls back to its default swing.",
    "door on w1 at 50% width 800 swing into faraway   # warning: not on this wall",
  ),
  W_DOOR_OFF_WALL: W(
    "W_DOOR_OFF_WALL",
    "Door does not lie on any wall.",
    "A door's position is not within tolerance of any wall segment, so it has no host.",
    "Move the door onto a wall, or name its host with `wall <id|category>`. The diagnostic points at the nearest wall.",
    "door at (9999,9999) width 900   # warning: not on a wall",
  ),
  W_EMPTY_PLAN: W(
    "W_EMPTY_PLAN",
    "Empty plan.",
    "The plan resolved to no drawable elements.",
    "Add at least one element (wall, room, …).",
    'plan "Empty" { units mm }   # warning',
  ),
  W_HATCH_SCALE: W(
    "W_HATCH_SCALE",
    "Hatch scale must be positive; using 1.",
    "A wall material `scale` evaluated to zero or a negative number.",
    "Use a positive `scale`.",
    "wall exterior thickness 200 material brick scale 0 { (0,0) (1,0) }",
  ),
  W_ROOM_OVERLAP: W(
    "W_ROOM_OVERLAP",
    "Rooms overlap.",
    "Two room rectangles intersect.",
    "Adjust positions/sizes if the overlap is unintended (it is allowed).",
    "room at (0,0) size 2000x2000\nroom at (1000,0) size 2000x2000   # warning",
  ),
  W_SANITIZED_CONFIG: W(
    "W_SANITIZED_CONFIG",
    "A disallowed config value was stripped.",
    "A theme/style value contained markup or a `data:` URL and was blanked for safety.",
    "Use a plain colour/string value (no `<`, `>`, or `url(data:…)`).",
    'theme { wall: "<script>" }   # warning: stripped',
  ),
  W_UNKNOWN_MATERIAL: W(
    "W_UNKNOWN_MATERIAL",
    "Unknown wall material; using the default hatch.",
    "A wall `material` name is not one of the known hatches.",
    "Use a known material (e.g. brick, concrete, insulation, tile) or omit it.",
    "wall exterior thickness 200 material marble { (0,0) (1,0) }   # warning",
  ),
  W_UNKNOWN_STYLE_KEY: W(
    "W_UNKNOWN_STYLE_KEY",
    "Unknown style key.",
    "A `style <kind> { … }` block uses a key not valid for that element kind.",
    "Use a valid key (e.g. fill / stroke / label, depending on the kind).",
    'style room { nope: "#000" }   # warning',
  ),
  W_UNKNOWN_THEME_KEY: W(
    "W_UNKNOWN_THEME_KEY",
    "Unknown theme key.",
    "A `theme { … }` block uses a key that is not a theme property or alias.",
    "Use a known theme key (see the language reference / hover).",
    'theme { nope: "#000" }   # warning',
  ),
  W_WINDOW_OFF_WALL: W(
    "W_WINDOW_OFF_WALL",
    "Window does not lie on any wall.",
    "A window's position is not within tolerance of any wall segment, so it has no host.",
    "Move the window onto a wall, or name its host with `wall <id|category>`. The diagnostic points at the nearest wall.",
    "window at (9999,9999) width 1200   # warning: not on a wall",
  ),
  W_OPENING_OFF_WALL: W(
    "W_OPENING_OFF_WALL",
    "Opening does not lie on any wall.",
    "A cased opening's position is not within tolerance of any wall segment, so it has no host.",
    "Move the opening onto a wall, or name its host with `wall <id|category>`. The diagnostic points at the nearest wall.",
    "opening at (9999,9999) width 1000   # warning: not on a wall",
  ),
  W_ROOM_UNREACHABLE: W(
    "W_ROOM_UNREACHABLE",
    "Room cannot be reached from the entrance.",
    "The building has an entrance, but this room has no door/opening path back to the exterior — it is sealed off from the circulation.",
    "Add a door or cased `opening` linking it (directly or through a hall) to a space that reaches the entrance.",
    'room at (5000,0) size 3000x3000 label "Store"   # lint: no path from the entrance',
  ),

  // Architectural lint rules (v1.1) — habitability checks raised by `arch lint`,
  // not the core compile pass. See src/lint.ts.
  W_BEDROOM_NO_WINDOW: W(
    "W_BEDROOM_NO_WINDOW",
    "Bedroom has no window.",
    "A room labelled as a bedroom has no window on its perimeter (natural light / egress).",
    "Add a `window` on an exterior wall of the room.",
    'room at (0,0) size 3000x4000 label "Bedroom"   # lint: no window',
  ),
  W_DOOR_CLEARANCE: W(
    "W_DOOR_CLEARANCE",
    "Door is narrower than the minimum clear width.",
    "A door's width is below the configured minimum passable width (default 700 mm).",
    "Widen the door to at least the minimum clear width.",
    "door at (0,0) width 500 wall exterior   # lint: under 700 mm",
  ),
  W_NO_ENTRANCE: W(
    "W_NO_ENTRANCE",
    "The plan has no exterior door.",
    "The plan has rooms and an exterior wall but no door hosted on an exterior wall, so the building cannot be entered.",
    "Add a `door` on an `exterior` wall.",
    "wall exterior thickness 200 { (0,0) (4000,0) (4000,3000) (0,3000) close }   # lint: no way in",
  ),
  W_ROOM_DISCONNECTED: W(
    "W_ROOM_DISCONNECTED",
    "Room has no door — it can't be entered.",
    "No door lies on any of the room's walls, so there is no way into the room.",
    "Add a `door` on one of the room's walls.",
    "room id=r at (0,0) size 3000x3000   # lint: no door on its perimeter",
  ),
  W_ROOM_LABEL_OUTSIDE: W(
    "W_ROOM_LABEL_OUTSIDE",
    "A room's explicit label anchor falls outside the room.",
    '`label "…" at (x,y)` pins the label and area text at a point that is not inside the room\'s floor, so the text will be drawn over whatever is there instead.',
    "Move the anchor inside the room, or drop the `at (…)` — automatic placement uses the rectangle's centre, the circle's centre, or a polygon's area centroid (falling back to the interior point furthest from any edge where a concave ring puts that centroid off its own floor), so it lands inside either way.",
    'room polygon (0,0) (6000,0) (6000,6000) (0,6000) label "Hall" at (9000,9000)   # warning',
  ),
  W_ROOM_TOO_SMALL: W(
    "W_ROOM_TOO_SMALL",
    "Room is implausibly small.",
    "A room's floor area is below the configured minimum (default 4 m²).",
    "Increase its `size`, or merge it into an adjacent space.",
    'room at (0,0) size 1000x1000 label "Closet"   # lint: 1 m²',
  ),
  W_BATH_VIA_BEDROOM: W(
    "W_BATH_VIA_BEDROOM",
    "Bathroom is reachable only through a bedroom.",
    "Every door path from the entrance to this bathroom/WC passes through a bedroom. That is fine for a private en-suite, but a dwelling's main bathroom should open off circulation (a hall or living space), not a bedroom.",
    "Add a door connecting the bathroom to a hall/living space, or route circulation so it is not reached only via a bedroom.",
    "door id=d_bath at (5200,4000) width 800 wall partition   # lint: bath only off the bedroom",
  ),
  W_ROOM_NOT_ENCLOSED: W(
    "W_ROOM_NOT_ENCLOSED",
    "Bathroom is not fully enclosed.",
    "A run of this bathroom/WC's perimeter is not backed by a wall, so it is open to the adjacent space — a privacy problem for a wet room (a partition that stops short is the usual cause).",
    "Extend the partition so the room's perimeter is walled on all sides (a door/window in the wall is fine — only a missing wall counts).",
    "wall partition thickness 100 { (4000,0) (4000,4000) }   # lint: stops short, bath left open",
  ),
  W_SWING_OBSTRUCTED: W(
    "W_SWING_OBSTRUCTED",
    "Door swing is obstructed.",
    "The quarter-circle a door leaf sweeps overlaps a piece of furniture/fixture or another door's swing, so the door cannot open fully. The warning states the clear radius the swing needs, what it actually has, and the shortfall.",
    "Hang the leaf on the other jamb (`hinge left|right`) — a machine-applicable fix when the flipped swing is proved clear; or open it the other way (`swing in|out`), move the door along its wall, move the obstruction (`arch repair`), narrow the leaf to the width the warning quotes (never below the minimum passable width — that relocates the problem into `W_DOOR_CLEARANCE`), or make it a leafless `opening`.",
    "door at (4000,1500) width 900 swing in   # lint: leaf sweeps onto the bed",
  ),
  W_ROOM_NO_FIXTURE: W(
    "W_ROOM_NO_FIXTURE",
    "Bathroom or kitchen has no fixtures.",
    "A room labelled as a bathroom or kitchen contains no plumbing/kitchen fixture (WC, basin, shower, sink, counter…), so it is drawn as an empty box.",
    "Place the expected fixtures — e.g. import `lib/fixtures.arch` and add a `wc`, `basin`, `shower`, or `kitchen_sink`.",
    'room at (4000,4000) size 3000x2000 label "Bath"   # lint: no fixtures inside',
  ),
  W_FURNITURE_OVERLAP: W(
    "W_FURNITURE_OVERLAP",
    "Two pieces of furniture overlap.",
    "Two furniture/fixture rectangles occupy the same floor area, so they would physically collide — usually a coordinate or size mistake.",
    "Move or resize one so they no longer intersect; leave a walkway between them.",
    "furniture sofa at (300,300) size 2000x900\nfurniture bed  at (1000,500) size 1500x2000   # lint: overlaps the sofa",
  ),
  W_FIXTURE_FLOATING: W(
    "W_FIXTURE_FLOATING",
    "A plumbing/kitchen fixture is not against a wall.",
    "A fixture that conventionally needs a wall behind it (WC, basin, shower, sink, counter, stove, fridge…) sits with no wall backing any edge — it appears to float in the middle of the room.",
    "Move the fixture so one edge is against a wall (supply/waste/venting runs in the wall), or remove it.",
    "furniture wc at (3000,3000) size 400x700   # lint: no wall behind it",
  ),
  W_FIXTURE_BACK_TO_ROOM: W(
    "W_FIXTURE_BACK_TO_ROOM",
    "A fixture stands against a wall but faces the wrong way.",
    "A fixture whose symbol has a distinct back (a WC's cistern, a basin's tap, a counter's nosing) is touching a wall, but its back is turned to the room instead of to that wall — the drawing shows the WC's tank sticking into the floor space. Position right, quarter-turn wrong: fixture symbols are drawn with their back on the TOP edge, so `rotate` is what aims them (0 = back to the north, 90 = east, 180 = south, 270 = west). A rotation-symmetric symbol (a shower tray) never trips this, and a fixture touching no wall at all is `W_FIXTURE_FLOATING` instead.",
    "Add the `rotate` that puts the back on the walled edge — the machine-applicable fix inserts it when exactly one edge is walled. Better still, place the piece with `against wall <id>` or `in <room> anchor <edge>` and let the rotation be derived.",
    "furniture wc at (5200,5200) size 400x700   # warning: south wall behind it, cistern facing north",
  ),
  W_FURN_CLEARANCE: W(
    "W_FURN_CLEARANCE",
    "A fixture's use-space is blocked.",
    "The activity clearance directly in front of a fixture (WC, basin, sink, counter, stove…) is intruded by a free-standing piece of furniture, so the fixture can't be used comfortably. Other plumbing/kitchen fixtures are ignored, so a compact bathroom/kitchen run does not trip this. The warning states the catalogued clearance, the depth actually left, and the shortfall.",
    "Move or shrink the obstructing furniture by the shortfall the warning quotes, turn the fixture so its front faces clear floor (its back must stay on a wall), or move the fixture to a wall run with the clearance free in front of it.",
    "furniture stove at (0,0) size 600x600\nfurniture sofa at (0,650) size 2000x900   # lint: sofa blocks the stove front",
  ),
  W_FIXTURE_WRONG_ROOM: W(
    "W_FIXTURE_WRONG_ROOM",
    "Fixture sits outside its declared room.",
    "A furniture item declared `in <roomId>` has its centre outside that room's rectangle, so it is drawn in the wrong space.",
    "Move the fixture inside the named room, or correct the `in <roomId>`.",
    'furniture wc at (100,100) size 400x700 in bath   # lint: centre is not inside "bath"',
  ),
  W_FURNITURE_WALL_COLLISION: W(
    "W_FURNITURE_WALL_COLLISION",
    "Furniture penetrates a wall.",
    "A furniture/fixture rectangle intrudes into a wall's solid (it crosses the wall's thickness band rather than sitting flush against its face), so it would physically pass through the wall — a coordinate or size mistake. A piece merely touching the wall face is fine.",
    "Move or resize the piece so it sits fully inside the room (against the wall face, not through it), or anchor it with `against wall <id>`.",
    "furniture sofa at (350,2300) size 2000x900   # lint: crosses the partition at y3000",
  ),
  W_DOORWAY_BLOCKED: W(
    "W_DOORWAY_BLOCKED",
    "A doorway's landing is blocked.",
    "A piece of furniture/fixture sits in the clear landing space immediately on either side of a door opening, so you cannot pass through the doorway even when the leaf is open. This is the approach path, distinct from the leaf's swing arc (`W_SWING_OBSTRUCTED`). The warning states the landing depth required, the depth actually left, and the shortfall.",
    "Move the obstruction clear of the opening by the shortfall the warning quotes (`arch repair` computes the smallest clearing shift), shrink it by that much on the axis facing the door, or move the door along its wall so its landing misses it.",
    "door at (6000,3000) width 800\nfurniture wc at (5800,3050) size 700x400   # lint: WC blocks the doorway",
  ),
  W_ROOM_NO_CLEAR_PATH: W(
    "W_ROOM_NO_CLEAR_PATH",
    "A room cannot be entered or crossed.",
    "Furniture, fixtures, door swings and their clearances fill the room so densely that a person stepping through a door/opening has no clear floor path into the usable space — the room is technically reachable but physically blocked.",
    "Open up the layout: move or shrink the furniture nearest the door so there is a continuous walkable strip from each entrance into the room.",
    "furniture shower at (5000,3000) size 2000x2000   # lint: fills the bathroom against its only door",
  ),
  W_PATH_TOO_NARROW: W(
    "W_PATH_TOO_NARROW",
    "The walk to a room squeezes below a passable width.",
    "The widest route from the entrance into a room (or between a key pair of rooms, e.g. bedroom→bath) has an unavoidable pinch narrower than the minimum passable clear width — a too-narrow door/opening, or furniture crowding the way. A coarse fact from the circulation nav grid (ADR 0008); the number is grid-quantised.",
    "Widen the tightest door/opening on the route to at least the minimum, move the furniture pinching it, or add a second way in so the pinch is avoidable. There is no machine-applicable fix: the bottleneck is a nav-grid cell, not a named element, so nothing can be rewritten for you.",
    "door at (4000,1500) width 600\nfurniture cabinet at (3600,300) size 700x1200   # lint: the way through squeezes below 700 mm",
  ),
  W_CIRCUITOUS_PATH: W(
    "W_CIRCUITOUS_PATH",
    "A room is reached by a very roundabout path.",
    "The walking distance from the entrance to a room is many times its straight-line distance — the room is reachable but only by a circuitous route (e.g. all the way around the plan). A coarse circulation fact (ADR 0008); the default ratio is generous so a normal tucked-away room does not trip it.",
    "Add a more direct connection — a door or a hall — so the room is not reached the long way round.",
    'room id=bed at (0,0) size 3000x3000 label "Bed"   # only door is on the far side, forcing a long detour',
  ),
  W_ALIAS_MATCH: W(
    "W_ALIAS_MATCH",
    "A room's use was inferred from an indirect alias, not stated.",
    "A room has no authored `uses`, and its function was guessed from its label via a non-canonical alias (an indirect term like `powder` → WC, `foyer` → entry) rather than a direct word (`wc`, `entrance`). The guess is reasonable but the intent is implicit, so a reader (or agent) cannot tell the classification was assumed.",
    "Add an explicit `uses …` to the room stating the inferred function — the machine-applicable fix inserts it for you. This pins the classification without changing the room's `describe()` type.",
    'room at (0,0) size 2000x1500 label "Powder"   # warning: WC inferred from the alias "powder"; add `uses wc`',
  ),
  W_DIM_NO_WALL: W(
    "W_DIM_NO_WALL",
    "A `dim faces`/`dim clear` endpoint has no wall to measure to.",
    "The endpoint-projection forms push each endpoint onto the FACE of the wall the measurement runs into, found as the nearest wall segment perpendicular to the dimension's own direction. One (or both) endpoints has no such wall within tolerance — the point is off the wall centerline, the wall is angled, or the plan has no wall there — so there is no face to project onto and the written point is measured as-is.",
    "Put the endpoint on the centerline of the wall the dimension runs into (the room-rectangle corner coordinate), or drop the `faces`/`clear` keyword and write the face coordinate yourself.",
    "wall exterior thickness 200 { (0,0) (5000,0) (5000,4000) (0,4000) close }\ndim faces (0,9000)->(5000,9000) offset 600   # warning: nothing to project onto at y9000",
  ),
  W_DIM_INSIDE: W(
    "W_DIM_INSIDE",
    "A hand-written dimension line lands inside the building.",
    "A `dim`'s line is drawn at `offset` along the LEFT normal of from→to, so the ENDPOINT ORDER chooses which side it lands on. This dimension's line (not its witness lines) falls inside the room-extents bounding box, where it crosses room labels, furniture and poché instead of reading in the page margin. Almost always the endpoints are simply the wrong way round. Advisory: an interior dimension you actually want (a clear width inside a room) is legitimate — reverse it or leave the warning.",
    "Swap the two endpoints — the machine-applicable fix does it for you — or negate the `offset`.",
    'dim (0,6000)->(7000,6000) offset -500 text "7000"   # warning: the -500 offset pulls the line back inside',
  ),
  W_DIM_OVERLAP: W(
    "W_DIM_OVERLAP",
    "Two hand-written dimensions are drawn on top of each other.",
    "Two `dim` statements measuring PARALLEL runs land in the same chain tier: their drawn bands — the dimension line, its station ticks, and the length text riding above the line — intersect, so on paper one reads through the other. ArchLang never re-staggers a hand-written dimension (the author's `offset` IS the tier control — ADR 0005, no invisible architect), so the collision is reported rather than silently laid out. Adjacent members of one chain that merely SHARE a station tick are not a collision and never warn, and two dims generated by one `for` are skipped — they share an `offset` expression, so no bump could separate them.",
    "Move one of them out a tier: raise the magnitude of its `offset` (keeping its sign, which is the side it reads on). The machine-applicable fix computes the smallest whole number of chain tiers that clears the other dimension's line and text.",
    'dim (0,-100)->(7000,-100) offset -300 text "7000"\ndim (0,-100)->(4000,-100) offset -300 text "4000"   # warning: both in the same tier',
  ),
  W_SCALE_OVERFLOW: W(
    "W_SCALE_OVERFLOW",
    "The drawing does not fit the declared paper at the declared scale.",
    "The plan declares a `paper` size, so `scale` is operative: the building's outer-face extent has to fit the sheet minus its margins, the `dims auto` dimension bands and the bottom chrome band (scale bar + title block). At the scale in force it does not. Your scale is NEVER silently overridden — a drawing is issued at the scale printed in its own title block — so the page simply grows past the sheet to contain the whole drawing. Advisory: an oversize sheet you intend to trim or tile is legitimate.",
    "Pick a coarser scale (a larger denominator draws the building smaller), move up a paper size, or drop the `scale` line and let the sheet auto-fit choose the finest scale from 1:50 / 1:100 / 1:200 / 1:500.",
    "paper A4 landscape\nscale 1:50   # warning on a 20 m building: 1:100 or `paper A2` fits, or omit `scale` to auto-fit",
  ),
  W_STAIR_UNMATCHED: W(
    "W_STAIR_UNMATCHED",
    "A run of vertical circulation appears on only one storey.",
    "In a multi-storey plan the ONLY thing that joins two floors is identity: a `stair`/`elevator`/`escalator` with the same `id` in two `level` blocks is one shaft. This id appears on exactly one storey, so it connects nothing — usually a typo in the id, or the matching run was never drawn on the floor above or below. **Known limitation:** a top-floor stair that genuinely goes only to a roof hatch, and a lift that stops short of a storey it passes, both trip this rule; it is advisory, so leave it.",
    "Draw the same run with the SAME `id` on the neighbouring storey (each storey declares its own `dir` — `up` on the lower floor, `down` on the upper one), or fix the id.",
    'level 1 "G" { stair id=s at (0,0) size 900x2600 dir up }\nlevel 2 "1" { }   # warning: "s" is on level 1 only',
  ),
  W_ROOM_NOT_EQUATOR_FACING: W(
    "W_ROOM_NOT_EQUATOR_FACING",
    "A habitable room has windows, but none faces the equator side.",
    "The plan declares `site`, so the equator-facing side is known (`S` in the northern hemisphere, `N` in the southern), and a habitable room — a bedroom, living or dining space — has at least one window with none of them on that aspect. **This is a drafting heuristic, not a measured daylight outcome:** it says the room's windows do not face the equator, and nothing more. A south window in Reykjavík and one in Singapore are not the same daylight, and this rule does not distinguish them (there is no sun model, latitude or date anywhere in ArchLang). The rule cannot fire at all in a plan with no `site`, and a room with NO window is `W_BEDROOM_NO_WINDOW`'s report, not this one.",
    "Move a window onto the room's equator-facing facade, or accept the aspect — an urban plot often has no equator-facing wall to spare. There is deliberately NO machine fix: the remedy is a geometric decision (which facade, which wall, what else it displaces) and the compiler does not make those (ADR 0005).",
    'site { street north }   # equator side is S\nroom id=liv at (0,0) size 4000x3000 label "Living"\nwindow on north_wall at 50% width 1200   # warning: the only window faces N',
  ),
});

/** All catalog codes, sorted (errors then warnings, alphabetically within). */
export const ERROR_CODES: readonly string[] = Object.keys(ERROR_CATALOG).sort((a, b) => {
  const sev = (c: string): number => (ERROR_CATALOG[c]!.severity === "error" ? 0 : 1);
  return sev(a) - sev(b) || a.localeCompare(b);
});

/** Render a catalog entry as a plain-text block for `arch explain`, or null. */
export function explain(code: string): string | null {
  const e = ERROR_CATALOG[code];
  if (!e) return null;
  return [
    `${e.code}  (${e.severity})`,
    `  ${e.message}`,
    "",
    "Cause:",
    `  ${e.cause}`,
    "",
    "Fix:",
    `  ${e.fix}`,
    "",
    "Example:",
    ...e.example.split("\n").map((l) => `  ${l}`),
  ].join("\n");
}
